const LANGS = [
  { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
  { code: 'th', label: 'ไทย', flag: '🇹🇭' },
  { code: 'km', label: 'ខ្មែរ', flag: '🇰🇭' },
  { code: 'id', label: 'Indonesia', flag: '🇮🇩' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', label: 'Português', flag: '🇵🇹' },
  { code: 'ar', label: 'العربية', flag: '🇸🇦' },
  { code: 'hi', label: 'हिन्दी', flag: '🇮🇳' }
];

const translations = {
  vi: {
    brand_tagline: "Agency Facebook", nav_about: "Về chúng tôi", nav_services: "Dịch vụ", nav_why: "Vì sao chọn chúng tôi", nav_process: "Quy trình", nav_testimonials: "Khách hàng", nav_faq: "Câu hỏi", nav_contact: "Liên hệ", nav_cta: "Tư vấn ngay",
    hero_badge: "5+ năm uy tín hàng đầu", hero_title: "Đối tác Agency Facebook uy tín hàng đầu", hero_subtitle: "Hơn 5 năm cung cấp tài khoản quảng cáo, Business Manager, thẻ thanh toán quốc tế và giải pháp chạy ads cho hàng nghìn agency và doanh nghiệp trên toàn cầu.", hero_cta_primary: "Nhận tư vấn miễn phí", hero_cta_secondary: "Xem dịch vụ", stat1_label: "Năm kinh nghiệm", stat2_label: "Khách hàng tin dùng", stat3_label: "Quốc gia phục vụ", stat4_label: "Hỗ trợ kỹ thuật",
    about_tag: "Về chúng tôi", about_title: "5 năm đồng hành cùng cộng đồng chạy quảng cáo quốc tế", about_desc: "Chúng tôi là đơn vị chuyên cung cấp Agency Facebook cho agency và doanh nghiệp trên toàn thế giới, với cam kết chất lượng, minh bạch và hỗ trợ tận tâm 24/7.", about_li1: "Nguồn hàng ổn định, kiểm định kỹ trước khi bàn giao", about_li2: "Đội ngũ kỹ thuật xử lý sự cố nhanh chóng", about_li3: "Chính sách bảo hành và hoàn tiền rõ ràng", about_li4: "Hợp tác với hàng nghìn agency tại hơn 30 quốc gia",
    services_tag: "Dịch vụ", services_title: "Cung cấp dịch vụ đầy đủ, chất lượng", services_subtitle: "Giải pháp trọn gói giúp chiến dịch quảng cáo của bạn vận hành ổn định và hiệu quả", svc1_t: "Tài khoản quảng cáo", svc1_d: "Tài khoản quảng cáo đa quốc gia, ngưỡng cao, độ trust tốt, sẵn sàng chạy chiến dịch ngay.", svc2_t: "Business Manager", svc2_d: "BM full quyền, đã xác minh, ổn định lâu dài cho việc quản lý nhiều tài khoản quảng cáo.", svc3_t: "Thẻ thanh toán quốc tế", svc3_d: "Thẻ visa/mastercard ảo hỗ trợ thanh toán quảng cáo nhanh chóng, an toàn.", svc4_t: "Fanpage uy tín", svc4_d: "Fanpage chất lượng, đã được xác minh, phù hợp nhiều lĩnh vực kinh doanh.", svc5_t: "Proxy & bảo mật", svc5_d: "Proxy tốc độ cao, ổn định, giảm thiểu rủi ro khóa tài khoản.", svc6_t: "Hỗ trợ kháng checkpoint", svc6_d: "Đội ngũ chuyên xử lý sự cố, kháng checkpoint nhanh chóng 24/7.",
    why_tag: "Vì sao chọn chúng tôi", why_title: "Đối tác đáng tin cậy cho mọi chiến dịch", why_subtitle: "Uy tín được xây dựng qua hơn 5 năm hoạt động và hàng nghìn khách hàng hài lòng", why1_t: "Uy tín hàng đầu", why1_d: "5+ năm hoạt động minh bạch, được cộng đồng agency quốc tế tin tưởng.", why2_t: "Chất lượng đảm bảo", why2_d: "Mọi sản phẩm đều được kiểm định kỹ lưỡng trước khi bàn giao.", why3_t: "Hỗ trợ 24/7", why3_d: "Đội ngũ kỹ thuật luôn sẵn sàng hỗ trợ mọi lúc, mọi nơi.", why4_t: "Bảo hành rõ ràng", why4_d: "Chính sách bảo hành, thay thế minh bạch, bảo vệ quyền lợi khách hàng.",
    process_tag: "Quy trình", process_title: "Đơn giản - Nhanh chóng - Hiệu quả", process_subtitle: "Chỉ với 4 bước để bắt đầu chiến dịch quảng cáo của bạn", step1_t: "Liên hệ tư vấn", step1_d: "Gửi yêu cầu, đội ngũ tư vấn viên sẽ liên hệ trong vòng 15 phút.", step2_t: "Chọn giải pháp", step2_d: "Lựa chọn sản phẩm phù hợp với nhu cầu chiến dịch của bạn.", step3_t: "Bàn giao & thanh toán", step3_d: "Nhận sản phẩm nhanh chóng, thanh toán linh hoạt, an toàn.", step4_t: "Hỗ trợ vận hành", step4_d: "Đồng hành hỗ trợ trong suốt quá trình chạy chiến dịch.",
    partners_title: "Được tin dùng bởi các agency hàng đầu",
    testi_tag: "Khách hàng nói gì", testi_title: "Hàng nghìn khách hàng hài lòng", testi_subtitle: "Những chia sẻ thực tế từ đối tác của chúng tôi", t1_quote: "\"Dịch vụ chuyên nghiệp, tài khoản ổn định, hỗ trợ nhanh. Đã hợp tác hơn 3 năm và luôn hài lòng.\"", t1_name: "Nguyễn Minh Anh", t1_role: "Giám đốc Agency, TP.HCM", t2_quote: "\"Đội ngũ hỗ trợ kỹ thuật xử lý sự cố rất nhanh, giúp chiến dịch của chúng tôi không bị gián đoạn.\"", t2_name: "David Chen", t2_role: "Marketing Manager, Singapore",
    faq_tag: "FAQ", faq_title: "Câu hỏi thường gặp", q1: "Sản phẩm có được bảo hành không?", a1: "Có, tất cả sản phẩm đều được bảo hành và hỗ trợ thay thế theo chính sách rõ ràng, minh bạch.", q2: "Thời gian bàn giao sản phẩm là bao lâu?", a2: "Hầu hết sản phẩm được bàn giao trong vòng 15-30 phút sau khi xác nhận đơn hàng.", q3: "Có hỗ trợ khách hàng quốc tế không?", a3: "Có, chúng tôi phục vụ khách hàng tại hơn 30 quốc gia với đội ngũ hỗ trợ đa ngôn ngữ.", q4: "Phương thức thanh toán nào được chấp nhận?", a4: "Chúng tôi hỗ trợ nhiều phương thức thanh toán linh hoạt, an toàn phù hợp với từng khu vực.",
    contact_tag: "Liên hệ", contact_title: "Sẵn sàng bắt đầu chiến dịch của bạn?", contact_subtitle: "Nhắn tin trực tiếp cho chúng tôi qua Messenger hoặc Telegram — phản hồi nhanh chóng", contact_messenger: "Nhắn tin qua Messenger", contact_messenger_sub: "Trả lời nhanh trong giờ làm việc", contact_telegram: "Nhắn tin qua Telegram", contact_telegram_sub: "Kênh liên hệ nhanh 24/7", info_email_label: "Email", info_phone_label: "Điện thoại", info_address_label: "Địa chỉ", info_address: "TP. Hồ Chí Minh, Việt Nam", info_hours_label: "Giờ làm việc", info_hours: "24/7 — Tất cả các ngày trong tuần",
    footer_desc: "Đơn vị cung cấp Agency Facebook uy tín hàng đầu, đồng hành cùng agency và doanh nghiệp trên toàn cầu.", footer_rights: "Bảo lưu mọi quyền.", footer_cta: "Liên hệ tư vấn",
    chat_title: "Trợ lý AI", chat_status_offline: "● Chế độ FAQ tự động", chat_status_online: "● Đang hoạt động", chat_direct_label: "Cần người hỗ trợ trực tiếp?", chat_input_ph: "Nhập câu hỏi của bạn...", chat_greeting: "Xin chào! Mình là trợ lý ảo. Bạn cần hỗ trợ gì về dịch vụ Agency Facebook?", chat_fallback: "Cảm ơn câu hỏi của bạn! Để được tư vấn chi tiết nhất, hãy nhắn tin trực tiếp cho đội ngũ qua Messenger hoặc Telegram bên dưới nhé.", chat_q_price: "Giá cả thế nào?", chat_q_warranty: "Có bảo hành không?", chat_q_delivery: "Giao hàng bao lâu?", chat_q_contact: "Gặp nhân viên tư vấn", nav_company: "Doanh nghiệp", company_tag: "Hồ sơ doanh nghiệp", company_title: "Thông tin doanh nghiệp", company_subtitle: "Minh bạch thông tin pháp lý và không gian làm việc thực tế của chúng tôi", label_legal_name: "Tên pháp lý", label_tax_code: "Mã số thuế", label_founded: "Năm thành lập", label_hq_address: "Trụ sở chính", label_representative: "Người đại diện", label_scale: "Quy mô nhân sự", label_field: "Lĩnh vực hoạt động", gallery_empty_hint: "Ảnh doanh nghiệp sẽ hiển thị tại đây — thêm trong admin panel (icon ⚙ ở footer)", contact_whatsapp: "Nhắn tin qua WhatsApp", contact_whatsapp_sub: "Hỗ trợ khách hàng quốc tế", contact_wechat: "Nhắn tin qua WeChat", contact_wechat_sub: "Dành cho khách hàng khu vực Trung Quốc"
  },

  en: {
    brand_tagline: "Facebook Ads Resources", nav_about: "About", nav_services: "Services", nav_why: "Why Us", nav_process: "Process", nav_testimonials: "Testimonials", nav_faq: "FAQ", nav_contact: "Contact", nav_cta: "Get a Quote",
    hero_badge: "5+ Years Trusted Partner", hero_title: "A Leading, Trusted Partner for Facebook Ads Resources", hero_subtitle: "Over 5 years supplying ad accounts, Business Managers, international payment cards and ads solutions for thousands of agencies and businesses worldwide.", hero_cta_primary: "Get a Free Consultation", hero_cta_secondary: "View Services", stat1_label: "Years of experience", stat2_label: "Trusted clients", stat3_label: "Countries served", stat4_label: "Technical support",
    about_tag: "About Us", about_title: "5 Years Alongside the Global Ads Community", about_desc: "We are a dedicated provider of Facebook ads resources for agencies and businesses worldwide, committed to quality, transparency, and dedicated 24/7 support.", about_li1: "Stable supply, thoroughly verified before delivery", about_li2: "Technical team resolving issues quickly", about_li3: "Clear warranty and refund policy", about_li4: "Partnered with thousands of agencies across 30+ countries",
    services_tag: "Services", services_title: "Complete, High-Quality Facebook Ads Resources", services_subtitle: "All-in-one solutions to keep your ad campaigns running stable and effective", svc1_t: "Ad Accounts", svc1_d: "Multi-country ad accounts with high spending limits and strong trust score, ready to launch campaigns instantly.", svc2_t: "Business Manager", svc2_d: "Fully verified BM with full access, stable long-term for managing multiple ad accounts.", svc3_t: "International Payment Cards", svc3_d: "Virtual Visa/Mastercard cards for fast, secure ad payments.", svc4_t: "Trusted Fanpages", svc4_d: "Quality, verified fanpages suited to many business fields.", svc5_t: "Proxy & Security", svc5_d: "High-speed, stable proxies that minimize the risk of account bans.", svc6_t: "Checkpoint Recovery Support", svc6_d: "A dedicated team resolving issues and appealing checkpoints quickly, 24/7.",
    why_tag: "Why Choose Us", why_title: "A Reliable Partner for Every Campaign", why_subtitle: "Trust built over 5+ years of operation and thousands of satisfied clients", why1_t: "Leading Reputation", why1_d: "5+ years of transparent operation, trusted by the international agency community.", why2_t: "Guaranteed Quality", why2_d: "Every product is thoroughly verified before delivery.", why3_t: "24/7 Support", why3_d: "Our technical team is always ready to help, anytime, anywhere.", why4_t: "Clear Warranty", why4_d: "Transparent warranty and replacement policy that protects your rights.",
    process_tag: "Process", process_title: "Simple - Fast - Effective", process_subtitle: "Just 4 steps to start your ad campaign", step1_t: "Contact Us", step1_d: "Send your request and our consultants will reach out within 15 minutes.", step2_t: "Choose a Solution", step2_d: "Select the product that fits your campaign needs.", step3_t: "Delivery & Payment", step3_d: "Receive your product quickly with flexible, secure payment.", step4_t: "Ongoing Support", step4_d: "We stay with you throughout your entire campaign.",
    partners_title: "Trusted by Leading Agencies",
    testi_tag: "Testimonials", testi_title: "Thousands of Satisfied Clients", testi_subtitle: "Real feedback from our partners", t1_quote: "\"Professional service, stable accounts, fast support. We've worked together for over 3 years and are always satisfied.\"", t1_name: "Nguyen Minh Anh", t1_role: "Agency Director, Ho Chi Minh City", t2_quote: "\"The technical support team resolves issues very quickly, keeping our campaigns running without interruption.\"", t2_name: "David Chen", t2_role: "Marketing Manager, Singapore",
    faq_tag: "FAQ", faq_title: "Frequently Asked Questions", q1: "Are products covered by warranty?", a1: "Yes, all products come with a clear, transparent warranty and replacement policy.", q2: "How long does delivery take?", a2: "Most products are delivered within 15-30 minutes after order confirmation.", q3: "Do you support international clients?", a3: "Yes, we serve clients in 30+ countries with a multilingual support team.", q4: "What payment methods are accepted?", a4: "We support multiple flexible, secure payment methods tailored to each region.",
    contact_tag: "Contact", contact_title: "Ready to Launch Your Campaign?", contact_subtitle: "Message us directly on Messenger or Telegram — fast response", contact_messenger: "Message us on Messenger", contact_messenger_sub: "Fast replies during business hours", contact_telegram: "Message us on Telegram", contact_telegram_sub: "Quick 24/7 contact channel", info_email_label: "Email", info_phone_label: "Phone", info_address_label: "Address", info_address: "Ho Chi Minh City, Vietnam", info_hours_label: "Working Hours", info_hours: "24/7 — Every day of the week",
    footer_desc: "A leading, trusted provider of Facebook ads resources, partnering with agencies and businesses worldwide.", footer_rights: "All rights reserved.", footer_cta: "Contact Us",
    chat_title: "AI Assistant", chat_status_offline: "● Auto-FAQ mode", chat_status_online: "● Online", chat_direct_label: "Need a human?", chat_input_ph: "Type your question...", chat_greeting: "Hi! I'm your virtual assistant. What do you need help with regarding our Facebook ads resources?", chat_fallback: "Thanks for your question! For detailed help, please message our team directly via Messenger or Telegram below.", chat_q_price: "What are the prices?", chat_q_warranty: "Is there a warranty?", chat_q_delivery: "How fast is delivery?", chat_q_contact: "Talk to a consultant", nav_company: "Company", company_tag: "Company Profile", company_title: "Company Information", company_subtitle: "Transparent legal information and a real look at our workspace", label_legal_name: "Legal Name", label_tax_code: "Tax Code", label_founded: "Founded", label_hq_address: "Headquarters", label_representative: "Representative", label_scale: "Team Size", label_field: "Business Field", gallery_empty_hint: "Company photos will appear here — add them in the admin panel (⚙ icon in the footer)", contact_whatsapp: "Message us on WhatsApp", contact_whatsapp_sub: "Support for international clients", contact_wechat: "Message us on WeChat", contact_wechat_sub: "For clients in the China region"
  },

  zh: {
    brand_tagline: "Facebook广告素材资源", nav_about: "关于我们", nav_services: "服务项目", nav_why: "为何选择我们", nav_process: "合作流程", nav_testimonials: "客户评价", nav_faq: "常见问题", nav_contact: "联系我们", nav_cta: "立即咨询",
    hero_badge: "5年以上值得信赖的合作伙伴", hero_title: "值得信赖的Facebook广告资源领先供应商", hero_subtitle: "5年以上为全球数千家代理商和企业提供广告账户、Business Manager、国际支付卡及广告投放解决方案。", hero_cta_primary: "免费咨询", hero_cta_secondary: "查看服务", stat1_label: "年行业经验", stat2_label: "信赖客户", stat3_label: "服务国家", stat4_label: "技术支持",
    about_tag: "关于我们", about_title: "5年携手全球广告投放社区", about_desc: "我们专注于为全球代理商和企业提供Facebook广告资源，致力于品质保证、透明经营与全天候贴心服务。", about_li1: "货源稳定，交付前严格检测", about_li2: "技术团队快速处理问题", about_li3: "保修与退款政策清晰透明", about_li4: "与30多个国家的数千家代理商合作",
    services_tag: "服务项目", services_title: "全面优质的Facebook广告资源", services_subtitle: "一站式解决方案，让您的广告活动稳定高效运行", svc1_t: "广告账户", svc1_d: "多国广告账户，额度高、信任度好，可立即投放广告。", svc2_t: "Business Manager", svc2_d: "全权限已验证BM，长期稳定，便于管理多个广告账户。", svc3_t: "国际支付卡", svc3_d: "虚拟Visa/万事达卡，支持快速安全的广告支付。", svc4_t: "信誉主页", svc4_d: "优质已验证主页，适用于多种商业领域。", svc5_t: "代理与安全防护", svc5_d: "高速稳定代理，降低账户被封风险。", svc6_t: "申诉支持", svc6_d: "专业团队全天候快速处理问题及申诉。",
    why_tag: "为何选择我们", why_title: "每一次投放都值得信赖的伙伴", why_subtitle: "5年以上运营积累的信誉，数千客户的满意见证", why1_t: "领先信誉", why1_d: "5年以上透明运营，深受国际代理商社区信赖。", why2_t: "品质保证", why2_d: "所有产品交付前均经过严格检测。", why3_t: "全天候支持", why3_d: "技术团队随时随地为您提供帮助。", why4_t: "清晰保修", why4_d: "透明的保修与更换政策，保障客户权益。",
    process_tag: "合作流程", process_title: "简单 - 快速 - 高效", process_subtitle: "仅需4步即可开启您的广告活动", step1_t: "联系咨询", step1_d: "提交需求，顾问团队将在15分钟内联系您。", step2_t: "选择方案", step2_d: "选择符合您投放需求的产品。", step3_t: "交付与付款", step3_d: "快速交付产品，支付方式灵活安全。", step4_t: "运营支持", step4_d: "全程陪伴支持您的广告投放。",
    partners_title: "深受众多领先代理商信赖",
    testi_tag: "客户评价", testi_title: "数千客户的满意选择", testi_subtitle: "来自合作伙伴的真实反馈", t1_quote: "“服务专业，账户稳定，支持迅速。合作三年多，一直很满意。”", t1_name: "阮明英", t1_role: "代理商总监，胡志明市", t2_quote: "“技术支持团队处理问题非常迅速，让我们的广告活动从未中断。”", t2_name: "David Chen", t2_role: "市场经理，新加坡",
    faq_tag: "常见问题", faq_title: "常见问题解答", q1: "产品是否提供保修？", a1: "是的，所有产品均提供清晰透明的保修与更换政策。", q2: "产品交付需要多长时间？", a2: "大多数产品在订单确认后15-30分钟内交付。", q3: "是否支持国际客户？", a3: "是的，我们为30多个国家的客户提供服务，并配备多语言支持团队。", q4: "支持哪些付款方式？", a4: "我们支持多种灵活安全的付款方式，适配不同地区需求。",
    contact_tag: "联系我们", contact_title: "准备好开启您的广告活动了吗？", contact_subtitle: "通过Messenger或Telegram直接联系我们，快速响应", contact_messenger: "通过Messenger联系", contact_messenger_sub: "工作时间内快速回复", contact_telegram: "通过Telegram联系", contact_telegram_sub: "24/7快速联系渠道", info_email_label: "电子邮箱", info_phone_label: "电话", info_address_label: "地址", info_address: "越南胡志明市", info_hours_label: "工作时间", info_hours: "全天候 — 全年无休",
    footer_desc: "值得信赖的Facebook广告资源领先供应商，携手全球代理商与企业共同成长。", footer_rights: "版权所有。", footer_cta: "联系咨询",
    chat_title: "AI助手", chat_status_offline: "● 自动问答模式", chat_status_online: "● 在线", chat_direct_label: "需要人工协助？", chat_input_ph: "输入您的问题...", chat_greeting: "您好！我是虚拟助手，请问关于Facebook广告资源您需要什么帮助？", chat_fallback: "感谢您的提问！如需详细咨询，请通过下方Messenger或Telegram直接联系我们的团队。", chat_q_price: "价格是多少？", chat_q_warranty: "是否提供保修？", chat_q_delivery: "多久能交付？", chat_q_contact: "联系顾问", nav_company: "企业信息", company_tag: "企业档案", company_title: "企业信息", company_subtitle: "透明的法律信息与真实的办公环境展示", label_legal_name: "公司法定名称", label_tax_code: "税号", label_founded: "成立年份", label_hq_address: "总部地址", label_representative: "法定代表人", label_scale: "团队规模", label_field: "经营领域", gallery_empty_hint: "企业照片将显示在此处 — 请在管理面板中添加（页脚⚙图标）", contact_whatsapp: "通过WhatsApp联系", contact_whatsapp_sub: "为国际客户提供支持", contact_wechat: "通过微信联系", contact_wechat_sub: "面向中国地区客户"
  },

  ru: {
    brand_tagline: "Ресурсы для рекламы Facebook", nav_about: "О нас", nav_services: "Услуги", nav_why: "Почему мы", nav_process: "Процесс", nav_testimonials: "Отзывы", nav_faq: "Вопросы", nav_contact: "Контакты", nav_cta: "Получить консультацию",
    hero_badge: "Надёжный партнёр с 5-летним опытом", hero_title: "Ведущий надёжный поставщик ресурсов для рекламы Facebook", hero_subtitle: "Более 5 лет мы предоставляем рекламные аккаунты, Business Manager, международные платёжные карты и решения для запуска рекламы тысячам агентств и компаний по всему миру.", hero_cta_primary: "Бесплатная консультация", hero_cta_secondary: "Наши услуги", stat1_label: "Лет опыта", stat2_label: "Довольных клиентов", stat3_label: "Стран обслуживания", stat4_label: "Техподдержка",
    about_tag: "О нас", about_title: "5 лет вместе с мировым сообществом таргетологов", about_desc: "Мы — специализированный поставщик рекламных ресурсов Facebook для агентств и компаний по всему миру, гарантирующий качество, прозрачность и заботливую поддержку 24/7.", about_li1: "Стабильные поставки, тщательная проверка перед выдачей", about_li2: "Техническая команда быстро решает проблемы", about_li3: "Чёткая политика гарантии и возврата средств", about_li4: "Сотрудничество с тысячами агентств в 30+ странах",
    services_tag: "Услуги", services_title: "Полный спектр качественных ресурсов для рекламы Facebook", services_subtitle: "Комплексные решения для стабильной и эффективной работы ваших кампаний", svc1_t: "Рекламные аккаунты", svc1_d: "Аккаунты разных стран с высоким лимитом и хорошим трастом, готовы к запуску сразу.", svc2_t: "Business Manager", svc2_d: "Верифицированный BM с полным доступом, стабильный для управления несколькими аккаунтами.", svc3_t: "Международные платёжные карты", svc3_d: "Виртуальные карты Visa/Mastercard для быстрой и безопасной оплаты рекламы.", svc4_t: "Надёжные фан-страницы", svc4_d: "Качественные, верифицированные страницы для разных направлений бизнеса.", svc5_t: "Прокси и безопасность", svc5_d: "Быстрые и стабильные прокси, снижающие риск блокировки аккаунта.", svc6_t: "Помощь с чекпоинтами", svc6_d: "Команда специалистов быстро решает проблемы и снимает чекпоинты 24/7.",
    why_tag: "Почему мы", why_title: "Надёжный партнёр для любой кампании", why_subtitle: "Доверие, выстроенное за 5+ лет работы и тысячи довольных клиентов", why1_t: "Безупречная репутация", why1_d: "5+ лет прозрачной работы, которой доверяет международное сообщество агентств.", why2_t: "Гарантия качества", why2_d: "Каждый продукт тщательно проверяется перед выдачей.", why3_t: "Поддержка 24/7", why3_d: "Наша техническая команда всегда готова помочь в любое время.", why4_t: "Чёткая гарантия", why4_d: "Прозрачная политика гарантии и замены, защищающая интересы клиентов.",
    process_tag: "Процесс", process_title: "Просто - Быстро - Эффективно", process_subtitle: "Всего 4 шага, чтобы начать вашу рекламную кампанию", step1_t: "Свяжитесь с нами", step1_d: "Отправьте заявку, и наш консультант свяжется с вами в течение 15 минут.", step2_t: "Выберите решение", step2_d: "Подберите продукт, который подходит под задачи вашей кампании.", step3_t: "Выдача и оплата", step3_d: "Быстрое получение продукта, гибкая и безопасная оплата.", step4_t: "Поддержка в работе", step4_d: "Мы сопровождаем вас на протяжении всей кампании.",
    partners_title: "Нам доверяют ведущие агентства",
    testi_tag: "Отзывы", testi_title: "Тысячи довольных клиентов", testi_subtitle: "Реальные отзывы наших партнёров", t1_quote: "«Профессиональный сервис, стабильные аккаунты, быстрая поддержка. Сотрудничаем более 3 лет и всегда довольны».", t1_name: "Нгуен Минь Ань", t1_role: "Директор агентства, Хошимин", t2_quote: "«Техподдержка решает вопросы очень быстро, наши кампании работают без перебоев».", t2_name: "Дэвид Чен", t2_role: "Менеджер по маркетингу, Сингапур",
    faq_tag: "Вопросы", faq_title: "Часто задаваемые вопросы", q1: "Предоставляется ли гарантия на продукты?", a1: "Да, на все продукты действует чёткая и прозрачная политика гарантии и замены.", q2: "Сколько времени занимает выдача продукта?", a2: "Большинство продуктов выдаётся в течение 15-30 минут после подтверждения заказа.", q3: "Работаете ли вы с международными клиентами?", a3: "Да, мы обслуживаем клиентов в 30+ странах с помощью многоязычной команды поддержки.", q4: "Какие способы оплаты вы принимаете?", a4: "Мы поддерживаем множество гибких и безопасных способов оплаты для разных регионов.",
    contact_tag: "Контакты", contact_title: "Готовы запустить вашу кампанию?", contact_subtitle: "Напишите нам напрямую в Messenger или Telegram — быстрый ответ", contact_messenger: "Написать в Messenger", contact_messenger_sub: "Быстрые ответы в рабочее время", contact_telegram: "Написать в Telegram", contact_telegram_sub: "Быстрый канал связи 24/7", info_email_label: "Email", info_phone_label: "Телефон", info_address_label: "Адрес", info_address: "Хошимин, Вьетнам", info_hours_label: "Часы работы", info_hours: "24/7 — Каждый день недели",
    footer_desc: "Ведущий надёжный поставщик рекламных ресурсов Facebook, сотрудничающий с агентствами и компаниями по всему миру.", footer_rights: "Все права защищены.", footer_cta: "Связаться с нами",
    chat_title: "AI-ассистент", chat_status_offline: "● Режим авто-FAQ", chat_status_online: "● Онлайн", chat_direct_label: "Нужен живой человек?", chat_input_ph: "Введите ваш вопрос...", chat_greeting: "Здравствуйте! Я виртуальный ассистент. Чем могу помочь по ресурсам для рекламы Facebook?", chat_fallback: "Спасибо за вопрос! Для подробной консультации напишите нашей команде напрямую в Messenger или Telegram ниже.", chat_q_price: "Какие цены?", chat_q_warranty: "Есть гарантия?", chat_q_delivery: "Как быстро доставка?", chat_q_contact: "Связаться с консультантом", nav_company: "Компания", company_tag: "Профиль компании", company_title: "Информация о компании", company_subtitle: "Прозрачная юридическая информация и реальный вид нашего рабочего пространства", label_legal_name: "Юридическое название", label_tax_code: "Налоговый код", label_founded: "Год основания", label_hq_address: "Головной офис", label_representative: "Представитель", label_scale: "Размер команды", label_field: "Сфера деятельности", gallery_empty_hint: "Фотографии компании появятся здесь — добавьте их в панели администратора (значок ⚙ в футере)", contact_whatsapp: "Написать в WhatsApp", contact_whatsapp_sub: "Поддержка международных клиентов", contact_wechat: "Написать в WeChat", contact_wechat_sub: "Для клиентов из региона Китая"
  },

  ja: {
    brand_tagline: "Facebook広告リソース", nav_about: "会社概要", nav_services: "サービス", nav_why: "選ばれる理由", nav_process: "ご利用の流れ", nav_testimonials: "お客様の声", nav_faq: "よくある質問", nav_contact: "お問い合わせ", nav_cta: "今すぐ相談",
    hero_badge: "5年以上の信頼と実績", hero_title: "信頼できるFacebook広告リソースのリーディングパートナー", hero_subtitle: "5年以上にわたり、広告アカウント、ビジネスマネージャー、国際決済カード、広告運用ソリューションを世界中の何千もの代理店・企業に提供しています。", hero_cta_primary: "無料相談を申し込む", hero_cta_secondary: "サービスを見る", stat1_label: "年の実績", stat2_label: "信頼いただくお客様", stat3_label: "サービス提供国", stat4_label: "技術サポート",
    about_tag: "会社概要", about_title: "5年間、世界の広告運用コミュニティと共に", about_desc: "私たちは世界中の代理店・企業向けにFacebook広告リソースを提供する専門会社で、品質・透明性・24時間365日の丁寧なサポートをお約束します。", about_li1: "安定した供給、提供前の厳格な検証", about_li2: "迅速に問題を解決する技術チーム", about_li3: "明確な保証・返金ポリシー", about_li4: "30カ国以上、数千社の代理店との提携実績",
    services_tag: "サービス", services_title: "充実した高品質のFacebook広告リソース", services_subtitle: "広告キャンペーンを安定・効果的に運用するためのオールインワンソリューション", svc1_t: "広告アカウント", svc1_d: "多国籍対応・高い利用上限・高いトラストスコアで、すぐにキャンペーンを開始できます。", svc2_t: "ビジネスマネージャー", svc2_d: "認証済み・フルアクセス権限のBMで、複数アカウントの管理も長期的に安定。", svc3_t: "国際決済カード", svc3_d: "広告費の支払いを迅速・安全に行える仮想Visa/Mastercard。", svc4_t: "信頼性の高いファンページ", svc4_d: "認証済みで高品質、様々な業種に対応するファンページ。", svc5_t: "プロキシ＆セキュリティ", svc5_d: "高速・安定したプロキシでアカウント停止のリスクを軽減。", svc6_t: "チェックポイント対応サポート", svc6_d: "専門チームが24時間365日、迅速に問題解決・異議申し立てを対応。",
    why_tag: "選ばれる理由", why_title: "あらゆるキャンペーンに信頼できるパートナー", why_subtitle: "5年以上の実績と数千社のお客様満足によって築かれた信頼", why1_t: "業界トップクラスの信頼", why1_d: "5年以上の透明な運営で、世界の代理店コミュニティから信頼されています。", why2_t: "品質保証", why2_d: "すべての商品を提供前に厳格に検証します。", why3_t: "24時間365日サポート", why3_d: "技術チームがいつでもどこでもサポートいたします。", why4_t: "明確な保証制度", why4_d: "透明性のある保証・交換ポリシーでお客様の権利を保護します。",
    process_tag: "ご利用の流れ", process_title: "シンプル・スピーディー・効果的", process_subtitle: "わずか4ステップで広告キャンペーンを開始", step1_t: "お問い合わせ", step1_d: "ご要望をお送りいただければ、15分以内に担当者よりご連絡します。", step2_t: "ソリューションを選択", step2_d: "キャンペーンのニーズに合った商品をお選びください。", step3_t: "納品・お支払い", step3_d: "迅速な納品と柔軟で安全なお支払い方法。", step4_t: "運用サポート", step4_d: "キャンペーン期間中、継続的にサポートいたします。",
    partners_title: "大手代理店様にご信頼いただいています",
    testi_tag: "お客様の声", testi_title: "数千社のお客様にご満足いただいています", testi_subtitle: "パートナー様からのリアルな声", t1_quote: "「プロフェッショナルなサービス、安定したアカウント、迅速なサポート。3年以上の取引で常に満足しています。」", t1_name: "グエン・ミン・アイン", t1_role: "代理店ディレクター、ホーチミン市", t2_quote: "「技術サポートチームの対応が非常に速く、キャンペーンが中断することがありません。」", t2_name: "デイビッド・チェン", t2_role: "マーケティングマネージャー、シンガポール",
    faq_tag: "よくある質問", faq_title: "よくあるご質問", q1: "商品に保証は付いていますか？", a1: "はい、すべての商品に明確で透明性のある保証・交換ポリシーが適用されます。", q2: "納品までどのくらい時間がかかりますか？", a2: "ほとんどの商品は注文確認後15〜30分以内に納品されます。", q3: "海外のお客様にも対応していますか？", a3: "はい、30カ国以上のお客様に対応しており、多言語サポートチームを設けています。", q4: "どのような支払い方法に対応していますか？", a4: "地域ごとに柔軟で安全な複数の支払い方法に対応しています。",
    contact_tag: "お問い合わせ", contact_title: "キャンペーンを始める準備はできましたか？", contact_subtitle: "MessengerまたはTelegramで直接ご連絡ください — 迅速に対応します", contact_messenger: "Messengerで連絡する", contact_messenger_sub: "営業時間内に迅速に返信", contact_telegram: "Telegramで連絡する", contact_telegram_sub: "24時間対応の連絡窓口", info_email_label: "メール", info_phone_label: "電話", info_address_label: "住所", info_address: "ホーチミン市、ベトナム", info_hours_label: "営業時間", info_hours: "24時間365日対応",
    footer_desc: "世界中の代理店・企業と提携する、信頼できるFacebook広告リソースのリーディングプロバイダーです。", footer_rights: "全著作権所有。", footer_cta: "お問い合わせ",
    chat_title: "AIアシスタント", chat_status_offline: "● 自動FAQモード", chat_status_online: "● オンライン", chat_direct_label: "担当者と話したいですか？", chat_input_ph: "ご質問を入力してください...", chat_greeting: "こんにちは！バーチャルアシスタントです。Facebook広告リソースについて何かお手伝いできますか？", chat_fallback: "ご質問ありがとうございます！詳しいご相談は、下記のMessengerまたはTelegramより直接チームへご連絡ください。", chat_q_price: "料金はいくらですか？", chat_q_warranty: "保証はありますか？", chat_q_delivery: "納品までどれくらい？", chat_q_contact: "担当者に相談する", nav_company: "会社概要", company_tag: "企業プロフィール", company_title: "企業情報", company_subtitle: "透明性のある法人情報と実際のオフィスの様子", label_legal_name: "正式法人名", label_tax_code: "税番号", label_founded: "設立年", label_hq_address: "本社所在地", label_representative: "代表者", label_scale: "従業員数", label_field: "事業分野", gallery_empty_hint: "企業写真はここに表示されます — 管理パネル（フッターの⚙アイコン）から追加してください", contact_whatsapp: "WhatsAppでメッセージ", contact_whatsapp_sub: "海外のお客様向けサポート", contact_wechat: "WeChatでメッセージ", contact_wechat_sub: "中国地域のお客様向け"
  },

  ko: {
    brand_tagline: "페이스북 광고 리소스", nav_about: "회사 소개", nav_services: "서비스", nav_why: "선택 이유", nav_process: "진행 절차", nav_testimonials: "고객 후기", nav_faq: "자주 묻는 질문", nav_contact: "문의하기", nav_cta: "지금 상담하기",
    hero_badge: "5년 이상의 신뢰받는 파트너", hero_title: "믿을 수 있는 페이스북 광고 리소스 선두 공급업체", hero_subtitle: "5년 이상 전 세계 수천 개의 에이전시와 기업에 광고 계정, 비즈니스 매니저, 해외 결제 카드 및 광고 운영 솔루션을 제공해왔습니다.", hero_cta_primary: "무료 상담 신청", hero_cta_secondary: "서비스 보기", stat1_label: "년의 경력", stat2_label: "신뢰하는 고객", stat3_label: "서비스 국가", stat4_label: "기술 지원",
    about_tag: "회사 소개", about_title: "5년간 글로벌 광고 운영 커뮤니티와 함께", about_desc: "저희는 전 세계 에이전시와 기업을 위해 페이스북 광고 리소스를 전문적으로 제공하며, 품질과 투명성, 24시간 세심한 지원을 약속합니다.", about_li1: "안정적인 공급, 전달 전 철저한 검증", about_li2: "신속하게 문제를 해결하는 기술팀", about_li3: "명확한 보증 및 환불 정책", about_li4: "30개국 이상, 수천 개의 에이전시와 협력",
    services_tag: "서비스", services_title: "완비된 고품질 페이스북 광고 리소스", services_subtitle: "광고 캠페인을 안정적이고 효과적으로 운영할 수 있는 올인원 솔루션", svc1_t: "광고 계정", svc1_d: "다국적 광고 계정, 높은 지출 한도와 우수한 신뢰도로 즉시 캠페인 시작 가능.", svc2_t: "비즈니스 매니저", svc2_d: "인증된 전체 권한 BM으로 여러 광고 계정을 안정적으로 관리.", svc3_t: "해외 결제 카드", svc3_d: "빠르고 안전한 광고비 결제를 지원하는 가상 비자/마스터카드.", svc4_t: "신뢰할 수 있는 팬페이지", svc4_d: "다양한 비즈니스 분야에 적합한 고품질 인증 팬페이지.", svc5_t: "프록시 및 보안", svc5_d: "계정 정지 위험을 줄이는 고속 안정 프록시.", svc6_t: "체크포인트 해제 지원", svc6_d: "전문팀이 24시간 신속하게 문제 해결 및 이의 제기를 지원합니다.",
    why_tag: "선택 이유", why_title: "모든 캠페인에 신뢰할 수 있는 파트너", why_subtitle: "5년 이상의 운영과 수천 명의 만족한 고객이 쌓아온 신뢰", why1_t: "업계 최고의 신뢰도", why1_d: "5년 이상 투명하게 운영하며 국제 에이전시 커뮤니티의 신뢰를 받고 있습니다.", why2_t: "품질 보장", why2_d: "모든 제품은 전달 전 철저히 검증됩니다.", why3_t: "24시간 지원", why3_d: "기술팀이 언제 어디서나 도움을 드립니다.", why4_t: "명확한 보증", why4_d: "고객의 권리를 보호하는 투명한 보증 및 교체 정책.",
    process_tag: "진행 절차", process_title: "간단하고 - 빠르고 - 효과적으로", process_subtitle: "단 4단계로 광고 캠페인을 시작하세요", step1_t: "상담 문의", step1_d: "요청을 보내주시면 상담원이 15분 이내에 연락드립니다.", step2_t: "솔루션 선택", step2_d: "캠페인 요구에 맞는 제품을 선택하세요.", step3_t: "전달 및 결제", step3_d: "빠른 제품 전달과 유연하고 안전한 결제.", step4_t: "운영 지원", step4_d: "캠페인 진행 내내 함께 지원해드립니다.",
    partners_title: "선두 에이전시들이 신뢰하는 파트너",
    testi_tag: "고객 후기", testi_title: "수천 명의 만족한 고객", testi_subtitle: "파트너들의 실제 후기", t1_quote: "\"전문적인 서비스, 안정적인 계정, 빠른 지원. 3년 넘게 함께하며 항상 만족하고 있습니다.\"", t1_name: "응우옌 민 아인", t1_role: "에이전시 대표, 호치민시", t2_quote: "\"기술 지원팀이 문제를 매우 빠르게 해결해줘서 캠페인이 중단 없이 진행됩니다.\"", t2_name: "데이비드 첸", t2_role: "마케팅 매니저, 싱가포르",
    faq_tag: "FAQ", faq_title: "자주 묻는 질문", q1: "제품에 보증이 제공되나요?", a1: "네, 모든 제품에 명확하고 투명한 보증 및 교체 정책이 적용됩니다.", q2: "제품 전달까지 얼마나 걸리나요?", a2: "대부분의 제품은 주문 확인 후 15~30분 이내에 전달됩니다.", q3: "해외 고객도 지원하나요?", a3: "네, 30개국 이상의 고객을 다국어 지원팀과 함께 서비스하고 있습니다.", q4: "어떤 결제 방법을 지원하나요?", a4: "지역별로 유연하고 안전한 다양한 결제 방법을 지원합니다.",
    contact_tag: "문의하기", contact_title: "캠페인을 시작할 준비가 되셨나요?", contact_subtitle: "Messenger 또는 Telegram으로 직접 메시지를 보내주세요 — 빠른 응답", contact_messenger: "Messenger로 문의하기", contact_messenger_sub: "영업시간 내 빠른 답변", contact_telegram: "Telegram으로 문의하기", contact_telegram_sub: "24/7 빠른 연락 채널", info_email_label: "이메일", info_phone_label: "전화", info_address_label: "주소", info_address: "호치민시, 베트남", info_hours_label: "운영 시간", info_hours: "24시간 연중무휴",
    footer_desc: "전 세계 에이전시 및 기업과 협력하는 신뢰받는 페이스북 광고 리소스 선두 공급업체입니다.", footer_rights: "모든 권리 보유.", footer_cta: "문의하기",
    chat_title: "AI 어시스턴트", chat_status_offline: "● 자동 FAQ 모드", chat_status_online: "● 온라인", chat_direct_label: "상담원과 연결이 필요하신가요?", chat_input_ph: "질문을 입력하세요...", chat_greeting: "안녕하세요! 저는 가상 어시스턴트입니다. 페이스북 광고 리소스에 대해 무엇을 도와드릴까요?", chat_fallback: "질문 감사합니다! 자세한 상담은 아래 Messenger 또는 Telegram으로 팀에 직접 문의해 주세요.", chat_q_price: "가격이 어떻게 되나요?", chat_q_warranty: "보증이 되나요?", chat_q_delivery: "배송은 얼마나 걸리나요?", chat_q_contact: "상담원 연결", nav_company: "회사 정보", company_tag: "기업 프로필", company_title: "기업 정보", company_subtitle: "투명한 법적 정보와 실제 업무 공간을 소개합니다", label_legal_name: "법인명", label_tax_code: "사업자등록번호", label_founded: "설립연도", label_hq_address: "본사 주소", label_representative: "대표자", label_scale: "직원 규모", label_field: "사업 분야", gallery_empty_hint: "회사 사진이 여기에 표시됩니다 — 관리자 패널(하단 ⚙ 아이콘)에서 추가하세요", contact_whatsapp: "WhatsApp으로 문의하기", contact_whatsapp_sub: "해외 고객 지원", contact_wechat: "WeChat으로 문의하기", contact_wechat_sub: "중국 지역 고객 전용"
  },

  th: {
    brand_tagline: "ทรัพยากรโฆษณาเฟซบุ๊ก", nav_about: "เกี่ยวกับเรา", nav_services: "บริการ", nav_why: "ทำไมต้องเลือกเรา", nav_process: "ขั้นตอนการทำงาน", nav_testimonials: "ความคิดเห็นลูกค้า", nav_faq: "คำถามที่พบบ่อย", nav_contact: "ติดต่อเรา", nav_cta: "ปรึกษาตอนนี้",
    hero_badge: "พันธมิตรที่เชื่อถือได้กว่า 5 ปี", hero_title: "ผู้ให้บริการทรัพยากรโฆษณาเฟซบุ๊กที่น่าเชื่อถือชั้นนำ", hero_subtitle: "กว่า 5 ปีในการจัดหาบัญชีโฆษณา Business Manager บัตรชำระเงินระหว่างประเทศ และโซลูชันการยิงแอดให้กับเอเจนซี่และธุรกิจนับพันทั่วโลก", hero_cta_primary: "รับคำปรึกษาฟรี", hero_cta_secondary: "ดูบริการ", stat1_label: "ปีแห่งประสบการณ์", stat2_label: "ลูกค้าที่ไว้วางใจ", stat3_label: "ประเทศที่ให้บริการ", stat4_label: "ฝ่ายสนับสนุนทางเทคนิค",
    about_tag: "เกี่ยวกับเรา", about_title: "5 ปีเคียงข้างชุมชนนักการตลาดออนไลน์ทั่วโลก", about_desc: "เราคือผู้เชี่ยวชาญด้านทรัพยากรโฆษณาเฟซบุ๊กสำหรับเอเจนซี่และธุรกิจทั่วโลก ด้วยความมุ่งมั่นด้านคุณภาพ ความโปร่งใส และการสนับสนุนตลอด 24 ชั่วโมง", about_li1: "แหล่งสินค้ามั่นคง ตรวจสอบอย่างละเอียดก่อนส่งมอบ", about_li2: "ทีมเทคนิคแก้ไขปัญหาอย่างรวดเร็ว", about_li3: "นโยบายรับประกันและคืนเงินที่ชัดเจน", about_li4: "ร่วมมือกับเอเจนซี่นับพันแห่งในกว่า 30 ประเทศ",
    services_tag: "บริการ", services_title: "ทรัพยากรโฆษณาเฟซบุ๊กครบครัน คุณภาพสูง", services_subtitle: "โซลูชันครบวงจรที่ช่วยให้แคมเปญโฆษณาของคุณทำงานได้อย่างมั่นคงและมีประสิทธิภาพ", svc1_t: "บัญชีโฆษณา", svc1_d: "บัญชีโฆษณาหลายประเทศ วงเงินสูง ความน่าเชื่อถือดี พร้อมยิงแอดได้ทันที", svc2_t: "Business Manager", svc2_d: "BM สิทธิ์เต็ม ยืนยันตัวตนแล้ว มั่นคงระยะยาวสำหรับจัดการหลายบัญชีโฆษณา", svc3_t: "บัตรชำระเงินระหว่างประเทศ", svc3_d: "บัตร Visa/Mastercard เสมือนสำหรับชำระค่าโฆษณาอย่างรวดเร็วและปลอดภัย", svc4_t: "เพจที่น่าเชื่อถือ", svc4_d: "เพจคุณภาพ ยืนยันตัวตนแล้ว เหมาะกับหลากหลายธุรกิจ", svc5_t: "พร็อกซีและความปลอดภัย", svc5_d: "พร็อกซีความเร็วสูง เสถียร ลดความเสี่ยงบัญชีถูกระงับ", svc6_t: "บริการแก้ไข Checkpoint", svc6_d: "ทีมผู้เชี่ยวชาญแก้ไขปัญหาและอุทธรณ์ Checkpoint อย่างรวดเร็วตลอด 24 ชั่วโมง",
    why_tag: "ทำไมต้องเลือกเรา", why_title: "พันธมิตรที่ไว้วางใจได้สำหรับทุกแคมเปญ", why_subtitle: "ความน่าเชื่อถือที่สร้างขึ้นมากว่า 5 ปี และลูกค้านับพันที่พึงพอใจ", why1_t: "ความน่าเชื่อถือชั้นนำ", why1_d: "ดำเนินธุรกิจอย่างโปร่งใสมากว่า 5 ปี ได้รับความไว้วางใจจากชุมชนเอเจนซี่นานาชาติ", why2_t: "รับประกันคุณภาพ", why2_d: "สินค้าทุกชิ้นผ่านการตรวจสอบอย่างละเอียดก่อนส่งมอบ", why3_t: "สนับสนุนตลอด 24 ชม.", why3_d: "ทีมเทคนิคพร้อมให้ความช่วยเหลือได้ทุกที่ทุกเวลา", why4_t: "การรับประกันที่ชัดเจน", why4_d: "นโยบายรับประกันและเปลี่ยนสินค้าที่โปร่งใส ปกป้องสิทธิ์ของลูกค้า",
    process_tag: "ขั้นตอนการทำงาน", process_title: "ง่าย - รวดเร็ว - มีประสิทธิภาพ", process_subtitle: "เพียง 4 ขั้นตอนเพื่อเริ่มต้นแคมเปญโฆษณาของคุณ", step1_t: "ติดต่อสอบถาม", step1_d: "ส่งคำขอ ทีมที่ปรึกษาจะติดต่อกลับภายใน 15 นาที", step2_t: "เลือกโซลูชัน", step2_d: "เลือกสินค้าที่เหมาะกับความต้องการแคมเปญของคุณ", step3_t: "ส่งมอบและชำระเงิน", step3_d: "รับสินค้าอย่างรวดเร็ว ชำระเงินได้ยืดหยุ่นและปลอดภัย", step4_t: "สนับสนุนการดำเนินงาน", step4_d: "ร่วมเดินทางและสนับสนุนตลอดช่วงแคมเปญของคุณ",
    partners_title: "ได้รับความไว้วางใจจากเอเจนซี่ชั้นนำ",
    testi_tag: "ความคิดเห็นลูกค้า", testi_title: "ลูกค้านับพันที่พึงพอใจ", testi_subtitle: "เสียงตอบรับจริงจากพันธมิตรของเรา", t1_quote: "\"บริการมืออาชีพ บัญชีมั่นคง สนับสนุนรวดเร็ว ร่วมงานกันมากว่า 3 ปีและพึงพอใจเสมอ\"", t1_name: "เหงียน มินห์ อันห์", t1_role: "ผู้อำนวยการเอเจนซี่ นครโฮจิมินห์", t2_quote: "\"ทีมสนับสนุนทางเทคนิคแก้ไขปัญหาได้รวดเร็วมาก แคมเปญของเราจึงไม่เคยสะดุด\"", t2_name: "เดวิด เฉิน", t2_role: "ผู้จัดการฝ่ายการตลาด สิงคโปร์",
    faq_tag: "คำถามที่พบบ่อย", faq_title: "คำถามที่พบบ่อย", q1: "สินค้ามีการรับประกันหรือไม่?", a1: "มีครับ สินค้าทุกชิ้นมีนโยบายรับประกันและเปลี่ยนสินค้าที่ชัดเจนโปร่งใส", q2: "ใช้เวลาส่งมอบสินค้านานเท่าไหร่?", a2: "สินค้าส่วนใหญ่จะส่งมอบภายใน 15-30 นาทีหลังยืนยันคำสั่งซื้อ", q3: "รองรับลูกค้าต่างประเทศหรือไม่?", a3: "รองรับครับ เราให้บริการลูกค้าในกว่า 30 ประเทศ พร้อมทีมสนับสนุนหลายภาษา", q4: "รองรับการชำระเงินแบบใดบ้าง?", a4: "เรารองรับวิธีชำระเงินที่ยืดหยุ่นและปลอดภัยหลายรูปแบบตามแต่ละภูมิภาค",
    contact_tag: "ติดต่อเรา", contact_title: "พร้อมเริ่มต้นแคมเปญของคุณแล้วหรือยัง?", contact_subtitle: "ทักแชทเราโดยตรงผ่าน Messenger หรือ Telegram — ตอบกลับรวดเร็ว", contact_messenger: "แชทผ่าน Messenger", contact_messenger_sub: "ตอบกลับรวดเร็วในเวลาทำการ", contact_telegram: "แชทผ่าน Telegram", contact_telegram_sub: "ช่องทางติดต่อด่วน 24/7", info_email_label: "อีเมล", info_phone_label: "โทรศัพท์", info_address_label: "ที่อยู่", info_address: "นครโฮจิมินห์ ประเทศเวียดนาม", info_hours_label: "เวลาทำการ", info_hours: "24 ชั่วโมง ทุกวันไม่มีวันหยุด",
    footer_desc: "ผู้ให้บริการทรัพยากรโฆษณาเฟซบุ๊กที่น่าเชื่อถือชั้นนำ ร่วมมือกับเอเจนซี่และธุรกิจทั่วโลก", footer_rights: "สงวนลิขสิทธิ์ทั้งหมด", footer_cta: "ติดต่อปรึกษา",
    chat_title: "ผู้ช่วย AI", chat_status_offline: "● โหมด FAQ อัตโนมัติ", chat_status_online: "● ออนไลน์", chat_direct_label: "ต้องการคุยกับเจ้าหน้าที่?", chat_input_ph: "พิมพ์คำถามของคุณ...", chat_greeting: "สวัสดีค่ะ! ดิฉันคือผู้ช่วยเสมือน มีอะไรให้ช่วยเกี่ยวกับทรัพยากรโฆษณาเฟซบุ๊กไหมคะ?", chat_fallback: "ขอบคุณสำหรับคำถามค่ะ! สำหรับรายละเอียดเพิ่มเติม กรุณาแชทกับทีมงานโดยตรงผ่าน Messenger หรือ Telegram ด้านล่าง", chat_q_price: "ราคาเท่าไหร่?", chat_q_warranty: "มีการรับประกันไหม?", chat_q_delivery: "ส่งมอบเร็วแค่ไหน?", chat_q_contact: "คุยกับเจ้าหน้าที่", nav_company: "ข้อมูลบริษัท", company_tag: "โปรไฟล์บริษัท", company_title: "ข้อมูลบริษัท", company_subtitle: "ข้อมูลทางกฎหมายที่โปร่งใสและภาพจริงของสถานที่ทำงานของเรา", label_legal_name: "ชื่อนิติบุคคล", label_tax_code: "เลขประจำตัวผู้เสียภาษี", label_founded: "ปีที่ก่อตั้ง", label_hq_address: "ที่ตั้งสำนักงานใหญ่", label_representative: "ผู้แทนบริษัท", label_scale: "ขนาดทีมงาน", label_field: "สาขาธุรกิจ", gallery_empty_hint: "รูปภาพบริษัทจะแสดงที่นี่ — เพิ่มได้ในแผงผู้ดูแลระบบ (ไอคอน ⚙ ที่ท้ายเว็บไซต์)", contact_whatsapp: "แชทผ่าน WhatsApp", contact_whatsapp_sub: "รองรับลูกค้าต่างประเทศ", contact_wechat: "แชทผ่าน WeChat", contact_wechat_sub: "สำหรับลูกค้าในภูมิภาคจีน"
  },

  km: {
    brand_tagline: "ធនធានផ្សាយពាណិជ្ជកម្ម Facebook", nav_about: "អំពីយើង", nav_services: "សេវាកម្ម", nav_why: "ហេតុអ្វីជ្រើសរើសយើង", nav_process: "ដំណើរការ", nav_testimonials: "មតិអតិថិជន", nav_faq: "សំណួរញឹកញាប់", nav_contact: "ទាក់ទង", nav_cta: "សុំប្រឹក្សាឥឡូវនេះ",
    hero_badge: "ដៃគូជឿទុកចិត្តជាង៥ឆ្នាំ", hero_title: "ដៃគូផ្គត់ផ្គង់ធនធានផ្សាយពាណិជ្ជកម្ម Facebook ដែលគួរឱ្យទុកចិត្តឈានមុខគេ", hero_subtitle: "ជាង៥ឆ្នាំក្នុងការផ្គត់ផ្គង់គណនីផ្សាយពាណិជ្ជកម្ម Business Manager កាតទូទាត់អន្តរជាតិ និងដំណោះស្រាយផ្សាយពាណិជ្ជកម្មសម្រាប់ភ្នាក់ងារ និងអាជីវកម្មរាប់ពាន់នៅទូទាំងពិភពលោក។", hero_cta_primary: "ទទួលការប្រឹក្សាឥតគិតថ្លៃ", hero_cta_secondary: "មើលសេវាកម្ម", stat1_label: "ឆ្នាំបទពិសោធន៍", stat2_label: "អតិថិជនទុកចិត្ត", stat3_label: "ប្រទេសផ្តល់សេវា", stat4_label: "ជំនួយបច្ចេកទេស",
    about_tag: "អំពីយើង", about_title: "៥ឆ្នាំរួមដំណើរជាមួយសហគមន៍ផ្សាយពាណិជ្ជកម្មពិភពលោក", about_desc: "យើងគឺជាអ្នកផ្គត់ផ្គង់ធនធានផ្សាយពាណិជ្ជកម្ម Facebook ជំនាញសម្រាប់ភ្នាក់ងារ និងអាជីវកម្មទូទាំងពិភពលោក ដោយប្តេជ្ញាចិត្តលើគុណភាព តម្លាភាព និងការគាំទ្រ២៤ម៉ោង។", about_li1: "ប្រភពទំនិញមានស្ថេរភាព ត្រួតពិនិត្យយ៉ាងម៉ត់ចត់មុនប្រគល់ជូន", about_li2: "ក្រុមបច្ចេកទេសដោះស្រាយបញ្ហាបានលឿន", about_li3: "គោលការណ៍ធានា និងសងប្រាក់វិញច្បាស់លាស់", about_li4: "សហការជាមួយភ្នាក់ងាររាប់ពាន់នៅជាង៣០ប្រទេស",
    services_tag: "សេវាកម្ម", services_title: "ធនធានផ្សាយពាណិជ្ជកម្ម Facebook ពេញលេញ គុណភាពខ្ពស់", services_subtitle: "ដំណោះស្រាយពេញលេញជួយឱ្យយុទ្ធនាការផ្សាយពាណិជ្ជកម្មរបស់អ្នកដំណើរការមានស្ថេរភាព និងមានប្រសិទ្ធភាព", svc1_t: "គណនីផ្សាយពាណិជ្ជកម្ម", svc1_d: "គណនីច្រើនប្រទេស កម្រិតចំណាយខ្ពស់ ជំនឿទុកចិត្តល្អ ត្រៀមរួចដំណើរការភ្លាមៗ។", svc2_t: "Business Manager", svc2_d: "BM សិទ្ធិពេញលេញ បានផ្ទៀងផ្ទាត់ មានស្ថេរភាពសម្រាប់គ្រប់គ្រងគណនីច្រើន។", svc3_t: "កាតទូទាត់អន្តរជាតិ", svc3_d: "កាត Visa/Mastercard និម្មិតសម្រាប់ការទូទាត់ផ្សាយពាណិជ្ជកម្មលឿន និងសុវត្ថិភាព។", svc4_t: "ទំព័រគួរឱ្យទុកចិត្ត", svc4_d: "ទំព័រគុណភាព បានផ្ទៀងផ្ទាត់ សមស្របសម្រាប់ធុរកិច្ចច្រើនប្រភេទ។", svc5_t: "ប្រូកស៊ី និងសុវត្ថិភាព", svc5_d: "ប្រូកស៊ីល្បឿនលឿន មានស្ថេរភាព កាត់បន្ថយហានិភ័យគណនីត្រូវបានផ្អាក។", svc6_t: "ជំនួយដោះស្រាយ Checkpoint", svc6_d: "ក្រុមអ្នកជំនាញដោះស្រាយបញ្ហា និងប្តឹងឧទ្ធរណ៍លឿនប្រចាំ២៤ម៉ោង។",
    why_tag: "ហេតុអ្វីជ្រើសរើសយើង", why_title: "ដៃគូគួរឱ្យទុកចិត្តសម្រាប់រាល់យុទ្ធនាការ", why_subtitle: "ការទុកចិត្តបង្កើតឡើងជាង៥ឆ្នាំ និងអតិថិជនរាប់ពាន់ដែលពេញចិត្ត", why1_t: "កេរ្តិ៍ឈ្មោះឈានមុខគេ", why1_d: "ប្រតិបត្តិការតម្លាភាពជាង៥ឆ្នាំ ត្រូវបានទុកចិត្តដោយសហគមន៍ភ្នាក់ងារអន្តរជាតិ។", why2_t: "ធានាគុណភាព", why2_d: "ផលិតផលទាំងអស់ត្រូវបានត្រួតពិនិត្យយ៉ាងម៉ត់ចត់មុនប្រគល់ជូន។", why3_t: "ជំនួយ២៤/៧", why3_d: "ក្រុមបច្ចេកទេសរបស់យើងតែងតែត្រៀមខ្លួនជួយគ្រប់ពេលវេលា។", why4_t: "ការធានាច្បាស់លាស់", why4_d: "គោលការណ៍ធានា និងផ្លាស់ប្តូរតម្លាភាព ការពារសិទ្ធិអតិថិជន។",
    process_tag: "ដំណើរការ", process_title: "សាមញ្ញ - លឿន - មានប្រសិទ្ធភាព", process_subtitle: "គ្រាន់តែ៤ជំហានដើម្បីចាប់ផ្តើមយុទ្ធនាការផ្សាយពាណិជ្ជកម្មរបស់អ្នក", step1_t: "ទាក់ទងសុំប្រឹក្សា", step1_d: "ផ្ញើសំណើ ក្រុមប្រឹក្សាយើងនឹងទាក់ទងក្នុងរយៈពេល១៥នាទី។", step2_t: "ជ្រើសរើសដំណោះស្រាយ", step2_d: "ជ្រើសរើសផលិតផលដែលសមស្របនឹងតម្រូវការយុទ្ធនាការរបស់អ្នក។", step3_t: "ប្រគល់ជូន និងទូទាត់", step3_d: "ទទួលផលិតផលបានលឿន ទូទាត់បានបត់បែន និងសុវត្ថិភាព។", step4_t: "ជំនួយប្រតិបត្តិការ", step4_d: "រួមដំណើរជួយអ្នកពេញមួយដំណើរការយុទ្ធនាការ។",
    partners_title: "ទុកចិត្តដោយភ្នាក់ងារឈានមុខគេ",
    testi_tag: "មតិអតិថិជន", testi_title: "អតិថិជនរាប់ពាន់ដែលពេញចិត្ត", testi_subtitle: "មតិពិតប្រាកដពីដៃគូរបស់យើង", t1_quote: "\"សេវាកម្មវិជ្ជាជីវៈ គណនីមានស្ថេរភាព ជំនួយលឿន។ បានសហការជាង៣ឆ្នាំ និងតែងតែពេញចិត្ត។\"", t1_name: "ង្វៀន មិញ អាញ", t1_role: "នាយកភ្នាក់ងារ ទីក្រុងហូជីមិញ", t2_quote: "\"ក្រុមជំនួយបច្ចេកទេសដោះស្រាយបញ្ហាបានលឿនណាស់ ធ្វើឱ្យយុទ្ធនាការរបស់យើងមិនដែលដាច់រលត់។\"", t2_name: "David Chen", t2_role: "អ្នកគ្រប់គ្រងទីផ្សារ សិង្ហបុរី",
    faq_tag: "សំណួរញឹកញាប់", faq_title: "សំណួរដែលសួរញឹកញាប់", q1: "តើផលិតផលមានការធានាដែរឬទេ?", a1: "បាទ/ចាស ផលិតផលទាំងអស់មានគោលការណ៍ធានា និងផ្លាស់ប្តូរច្បាស់លាស់ តម្លាភាព។", q2: "តើចំណាយពេលប៉ុន្មានដើម្បីប្រគល់ជូនផលិតផល?", a2: "ផលិតផលភាគច្រើនត្រូវបានប្រគល់ជូនក្នុងរយៈពេល១៥-៣០នាទីបន្ទាប់ពីបញ្ជាក់ការបញ្ជាទិញ។", q3: "តើមានជំនួយសម្រាប់អតិថិជនអន្តរជាតិដែរឬទេ?", a3: "បាទ/ចាស យើងបម្រើអតិថិជននៅជាង៣០ប្រទេស ជាមួយក្រុមជំនួយពហុភាសា។", q4: "តើទទួលយកវិធីទូទាត់អ្វីខ្លះ?", a4: "យើងគាំទ្រវិធីទូទាត់ជាច្រើនដែលបត់បែន និងសុវត្ថិភាពសមស្របនឹងតំបន់នីមួយៗ។",
    contact_tag: "ទាក់ទង", contact_title: "តើអ្នកត្រៀមខ្លួនចាប់ផ្តើមយុទ្ធនាការរបស់អ្នកហើយឬនៅ?", contact_subtitle: "សរសេរសារមកយើងផ្ទាល់តាម Messenger ឬ Telegram — ឆ្លើយតបលឿន", contact_messenger: "ផ្ញើសារតាម Messenger", contact_messenger_sub: "ឆ្លើយតបលឿនក្នុងម៉ោងធ្វើការ", contact_telegram: "ផ្ញើសារតាម Telegram", contact_telegram_sub: "ប៉ុស្តិ៍ទាក់ទងលឿន ២៤/៧", info_email_label: "អ៊ីមែល", info_phone_label: "ទូរស័ព្ទ", info_address_label: "អាសយដ្ឋាន", info_address: "ទីក្រុងហូជីមិញ វៀតណាម", info_hours_label: "ម៉ោងធ្វើការ", info_hours: "២៤/៧ — គ្រប់ថ្ងៃក្នុងសប្តាហ៍",
    footer_desc: "អ្នកផ្គត់ផ្គង់ធនធានផ្សាយពាណិជ្ជកម្ម Facebook ដែលគួរឱ្យទុកចិត្តឈានមុខគេ រួមដំណើរជាមួយភ្នាក់ងារ និងអាជីវកម្មទូទាំងពិភពលោក។", footer_rights: "រក្សាសិទ្ធិគ្រប់យ៉ាង។", footer_cta: "ទាក់ទងសុំប្រឹក្សា",
    chat_title: "ជំនួយការ AI", chat_status_offline: "● របៀប FAQ ស្វ័យប្រវត្តិ", chat_status_online: "● កំពុងអនឡាញ", chat_direct_label: "ត្រូវការនិយាយជាមួយបុគ្គលិកផ្ទាល់?", chat_input_ph: "វាយសំណួររបស់អ្នក...", chat_greeting: "សួស្តី! ខ្ញុំជាជំនួយការនិម្មិត។ តើអ្នកត្រូវការជំនួយអ្វីទាក់ទងនឹងធនធានផ្សាយពាណិជ្ជកម្ម Facebook?", chat_fallback: "អរគុណសម្រាប់សំណួររបស់អ្នក! សម្រាប់ព័ត៌មានលម្អិត សូមផ្ញើសារដោយផ្ទាល់ទៅក្រុមការងារតាម Messenger ឬ Telegram ខាងក្រោម។", chat_q_price: "តម្លៃប៉ុន្មាន?", chat_q_warranty: "មានការធានាទេ?", chat_q_delivery: "ប្រគល់ជូនលឿនប៉ុណ្ណា?", chat_q_contact: "និយាយជាមួយទីប្រឹក្សា", nav_company: "ព័ត៌មានក្រុមហ៊ុន", company_tag: "ទម្រង់ក្រុមហ៊ុន", company_title: "ព័ត៌មានក្រុមហ៊ុន", company_subtitle: "ព័ត៌មានផ្លូវច្បាប់ដ៏តម្លាភាព និងទិដ្ឋភាពពិតនៃកន្លែងធ្វើការរបស់យើង", label_legal_name: "ឈ្មោះនីតិបុគ្គល", label_tax_code: "លេខសម្គាល់អ្នកជាប់ពន្ធ", label_founded: "ឆ្នាំបង្កើត", label_hq_address: "ទីស្នាក់ការកណ្តាល", label_representative: "អ្នកតំណាង", label_scale: "ទំហំបុគ្គលិក", label_field: "វិស័យអាជីវកម្ម", gallery_empty_hint: "រូបភាពក្រុមហ៊ុននឹងបង្ហាញនៅទីនេះ — បន្ថែមនៅក្នុងផ្ទាំងគ្រប់គ្រង (រូបតំណាង ⚙ នៅបាតគេហទំព័រ)", contact_whatsapp: "ផ្ញើសារតាម WhatsApp", contact_whatsapp_sub: "គាំទ្រអតិថិជនអន្តរជាតិ", contact_wechat: "ផ្ញើសារតាម WeChat", contact_wechat_sub: "សម្រាប់អតិថិជននៅតំបន់ចិន"
  },

  id: {
    brand_tagline: "Sumber Daya Iklan Facebook", nav_about: "Tentang Kami", nav_services: "Layanan", nav_why: "Mengapa Kami", nav_process: "Proses", nav_testimonials: "Testimoni", nav_faq: "FAQ", nav_contact: "Kontak", nav_cta: "Konsultasi Sekarang",
    hero_badge: "Mitra Terpercaya 5+ Tahun", hero_title: "Mitra Terkemuka dan Terpercaya untuk Sumber Daya Iklan Facebook", hero_subtitle: "Lebih dari 5 tahun menyediakan akun iklan, Business Manager, kartu pembayaran internasional, dan solusi iklan untuk ribuan agensi dan bisnis di seluruh dunia.", hero_cta_primary: "Konsultasi Gratis", hero_cta_secondary: "Lihat Layanan", stat1_label: "Tahun pengalaman", stat2_label: "Klien terpercaya", stat3_label: "Negara dilayani", stat4_label: "Dukungan teknis",
    about_tag: "Tentang Kami", about_title: "5 Tahun Bersama Komunitas Iklan Global", about_desc: "Kami adalah penyedia khusus sumber daya iklan Facebook untuk agensi dan bisnis di seluruh dunia, berkomitmen pada kualitas, transparansi, dan dukungan penuh perhatian 24/7.", about_li1: "Pasokan stabil, diverifikasi ketat sebelum diserahkan", about_li2: "Tim teknis menyelesaikan masalah dengan cepat", about_li3: "Kebijakan garansi dan pengembalian dana yang jelas", about_li4: "Bermitra dengan ribuan agensi di 30+ negara",
    services_tag: "Layanan", services_title: "Sumber Daya Iklan Facebook Lengkap dan Berkualitas", services_subtitle: "Solusi menyeluruh agar kampanye iklan Anda berjalan stabil dan efektif", svc1_t: "Akun Iklan", svc1_d: "Akun iklan multi-negara, limit tinggi, tingkat kepercayaan baik, siap dipakai kampanye segera.", svc2_t: "Business Manager", svc2_d: "BM akses penuh, terverifikasi, stabil untuk mengelola banyak akun iklan.", svc3_t: "Kartu Pembayaran Internasional", svc3_d: "Kartu Visa/Mastercard virtual untuk pembayaran iklan yang cepat dan aman.", svc4_t: "Fanpage Terpercaya", svc4_d: "Fanpage berkualitas, terverifikasi, cocok untuk berbagai bidang bisnis.", svc5_t: "Proxy & Keamanan", svc5_d: "Proxy cepat dan stabil yang meminimalkan risiko akun diblokir.", svc6_t: "Dukungan Kaji Checkpoint", svc6_d: "Tim khusus menyelesaikan masalah dan mengajukan banding checkpoint dengan cepat, 24/7.",
    why_tag: "Mengapa Kami", why_title: "Mitra Tepercaya untuk Setiap Kampanye", why_subtitle: "Kepercayaan yang dibangun selama 5+ tahun beroperasi dan ribuan klien yang puas", why1_t: "Reputasi Terdepan", why1_d: "5+ tahun beroperasi secara transparan, dipercaya oleh komunitas agensi internasional.", why2_t: "Kualitas Terjamin", why2_d: "Setiap produk diverifikasi secara menyeluruh sebelum diserahkan.", why3_t: "Dukungan 24/7", why3_d: "Tim teknis kami selalu siap membantu kapan saja, di mana saja.", why4_t: "Garansi Jelas", why4_d: "Kebijakan garansi dan penggantian yang transparan, melindungi hak pelanggan.",
    process_tag: "Proses", process_title: "Sederhana - Cepat - Efektif", process_subtitle: "Hanya 4 langkah untuk memulai kampanye iklan Anda", step1_t: "Hubungi Kami", step1_d: "Kirim permintaan Anda, tim konsultan kami akan menghubungi dalam 15 menit.", step2_t: "Pilih Solusi", step2_d: "Pilih produk yang sesuai dengan kebutuhan kampanye Anda.", step3_t: "Serah Terima & Pembayaran", step3_d: "Terima produk dengan cepat, pembayaran fleksibel dan aman.", step4_t: "Dukungan Operasional", step4_d: "Kami mendampingi Anda selama seluruh masa kampanye.",
    partners_title: "Dipercaya oleh Agensi-Agensi Terkemuka",
    testi_tag: "Testimoni", testi_title: "Ribuan Klien Puas", testi_subtitle: "Ulasan nyata dari mitra kami", t1_quote: "\"Layanan profesional, akun stabil, dukungan cepat. Sudah bekerja sama lebih dari 3 tahun dan selalu puas.\"", t1_name: "Nguyen Minh Anh", t1_role: "Direktur Agensi, Kota Ho Chi Minh", t2_quote: "\"Tim dukungan teknis menyelesaikan masalah dengan sangat cepat, kampanye kami tidak pernah terganggu.\"", t2_name: "David Chen", t2_role: "Manajer Pemasaran, Singapura",
    faq_tag: "FAQ", faq_title: "Pertanyaan yang Sering Diajukan", q1: "Apakah produk memiliki garansi?", a1: "Ya, semua produk memiliki kebijakan garansi dan penggantian yang jelas dan transparan.", q2: "Berapa lama waktu pengiriman produk?", a2: "Sebagian besar produk dikirim dalam 15-30 menit setelah konfirmasi pesanan.", q3: "Apakah mendukung klien internasional?", a3: "Ya, kami melayani klien di 30+ negara dengan tim dukungan multibahasa.", q4: "Metode pembayaran apa saja yang diterima?", a4: "Kami mendukung berbagai metode pembayaran yang fleksibel dan aman sesuai wilayah masing-masing.",
    contact_tag: "Kontak", contact_title: "Siap Memulai Kampanye Anda?", contact_subtitle: "Chat langsung dengan kami via Messenger atau Telegram — respons cepat", contact_messenger: "Chat via Messenger", contact_messenger_sub: "Balasan cepat di jam kerja", contact_telegram: "Chat via Telegram", contact_telegram_sub: "Kanal kontak cepat 24/7", info_email_label: "Email", info_phone_label: "Telepon", info_address_label: "Alamat", info_address: "Kota Ho Chi Minh, Vietnam", info_hours_label: "Jam Kerja", info_hours: "24/7 — Setiap hari dalam seminggu",
    footer_desc: "Penyedia sumber daya iklan Facebook terkemuka dan tepercaya, bermitra dengan agensi dan bisnis di seluruh dunia.", footer_rights: "Semua hak dilindungi.", footer_cta: "Hubungi Kami",
    chat_title: "Asisten AI", chat_status_offline: "● Mode FAQ otomatis", chat_status_online: "● Online", chat_direct_label: "Butuh bantuan langsung dari manusia?", chat_input_ph: "Ketik pertanyaan Anda...", chat_greeting: "Halo! Saya asisten virtual. Ada yang bisa saya bantu terkait sumber daya iklan Facebook?", chat_fallback: "Terima kasih atas pertanyaannya! Untuk bantuan lebih detail, silakan chat langsung tim kami via Messenger atau Telegram di bawah.", chat_q_price: "Berapa harganya?", chat_q_warranty: "Apakah ada garansi?", chat_q_delivery: "Berapa lama pengiriman?", chat_q_contact: "Bicara dengan konsultan", nav_company: "Perusahaan", company_tag: "Profil Perusahaan", company_title: "Informasi Perusahaan", company_subtitle: "Informasi legal yang transparan dan gambaran nyata ruang kerja kami", label_legal_name: "Nama Badan Hukum", label_tax_code: "NPWP", label_founded: "Tahun Didirikan", label_hq_address: "Kantor Pusat", label_representative: "Perwakilan", label_scale: "Jumlah Karyawan", label_field: "Bidang Usaha", gallery_empty_hint: "Foto perusahaan akan muncul di sini — tambahkan melalui panel admin (ikon ⚙ di footer)", contact_whatsapp: "Chat via WhatsApp", contact_whatsapp_sub: "Dukungan untuk klien internasional", contact_wechat: "Chat via WeChat", contact_wechat_sub: "Untuk klien di wilayah Tiongkok"
  },

  es: {
    brand_tagline: "Recursos para Anuncios de Facebook", nav_about: "Nosotros", nav_services: "Servicios", nav_why: "Por qué elegirnos", nav_process: "Proceso", nav_testimonials: "Testimonios", nav_faq: "Preguntas frecuentes", nav_contact: "Contacto", nav_cta: "Consultar ahora",
    hero_badge: "Socio de confianza con más de 5 años", hero_title: "Socio líder y confiable en recursos para anuncios de Facebook", hero_subtitle: "Más de 5 años suministrando cuentas publicitarias, Business Manager, tarjetas de pago internacionales y soluciones publicitarias a miles de agencias y empresas en todo el mundo.", hero_cta_primary: "Solicitar asesoría gratuita", hero_cta_secondary: "Ver servicios", stat1_label: "Años de experiencia", stat2_label: "Clientes que confían", stat3_label: "Países atendidos", stat4_label: "Soporte técnico",
    about_tag: "Sobre nosotros", about_title: "5 años junto a la comunidad global de publicidad", about_desc: "Somos un proveedor especializado en recursos para anuncios de Facebook para agencias y empresas de todo el mundo, comprometidos con la calidad, la transparencia y un soporte dedicado 24/7.", about_li1: "Suministro estable, verificado minuciosamente antes de la entrega", about_li2: "Equipo técnico que resuelve incidencias rápidamente", about_li3: "Política clara de garantía y reembolso", about_li4: "Aliados de miles de agencias en más de 30 países",
    services_tag: "Servicios", services_title: "Recursos completos y de calidad para anuncios de Facebook", services_subtitle: "Soluciones integrales para que tus campañas funcionen de forma estable y eficaz", svc1_t: "Cuentas publicitarias", svc1_d: "Cuentas de múltiples países, límites altos y buena confianza, listas para lanzar campañas de inmediato.", svc2_t: "Business Manager", svc2_d: "BM verificado con acceso total, estable a largo plazo para gestionar varias cuentas publicitarias.", svc3_t: "Tarjetas de pago internacionales", svc3_d: "Tarjetas Visa/Mastercard virtuales para pagos publicitarios rápidos y seguros.", svc4_t: "Fanpages confiables", svc4_d: "Páginas de calidad y verificadas, adecuadas para múltiples sectores.", svc5_t: "Proxy y seguridad", svc5_d: "Proxies estables y de alta velocidad que reducen el riesgo de bloqueo de cuentas.", svc6_t: "Soporte para checkpoints", svc6_d: "Equipo especializado que resuelve incidencias y apela checkpoints rápidamente, 24/7.",
    why_tag: "Por qué elegirnos", why_title: "Un socio confiable para cada campaña", why_subtitle: "Confianza construida durante más de 5 años y miles de clientes satisfechos", why1_t: "Reputación líder", why1_d: "Más de 5 años de operación transparente, con la confianza de la comunidad internacional de agencias.", why2_t: "Calidad garantizada", why2_d: "Cada producto se verifica minuciosamente antes de la entrega.", why3_t: "Soporte 24/7", why3_d: "Nuestro equipo técnico está siempre listo para ayudar, en cualquier momento y lugar.", why4_t: "Garantía clara", why4_d: "Política de garantía y reemplazo transparente que protege los derechos del cliente.",
    process_tag: "Proceso", process_title: "Simple - Rápido - Eficaz", process_subtitle: "Solo 4 pasos para iniciar tu campaña publicitaria", step1_t: "Contáctanos", step1_d: "Envía tu solicitud y nuestro equipo te contactará en 15 minutos.", step2_t: "Elige una solución", step2_d: "Selecciona el producto que se adapte a tu campaña.", step3_t: "Entrega y pago", step3_d: "Recibe tu producto rápidamente con un pago flexible y seguro.", step4_t: "Soporte continuo", step4_d: "Te acompañamos durante toda tu campaña.",
    partners_title: "Con la confianza de las principales agencias",
    testi_tag: "Testimonios", testi_title: "Miles de clientes satisfechos", testi_subtitle: "Opiniones reales de nuestros socios", t1_quote: "\"Servicio profesional, cuentas estables, soporte rápido. Llevamos más de 3 años trabajando juntos y siempre satisfechos.\"", t1_name: "Nguyen Minh Anh", t1_role: "Directora de Agencia, Ciudad Ho Chi Minh", t2_quote: "\"El equipo de soporte técnico resuelve los problemas muy rápido, nuestras campañas nunca se interrumpen.\"", t2_name: "David Chen", t2_role: "Gerente de Marketing, Singapur",
    faq_tag: "Preguntas frecuentes", faq_title: "Preguntas frecuentes", q1: "¿Los productos tienen garantía?", a1: "Sí, todos los productos cuentan con una política de garantía y reemplazo clara y transparente.", q2: "¿Cuánto tiempo tarda la entrega?", a2: "La mayoría de los productos se entregan en 15-30 minutos tras confirmar el pedido.", q3: "¿Atienden a clientes internacionales?", a3: "Sí, atendemos a clientes en más de 30 países con un equipo de soporte multilingüe.", q4: "¿Qué métodos de pago aceptan?", a4: "Admitimos múltiples métodos de pago flexibles y seguros adaptados a cada región.",
    contact_tag: "Contacto", contact_title: "¿Listo para lanzar tu campaña?", contact_subtitle: "Escríbenos directamente por Messenger o Telegram — respuesta rápida", contact_messenger: "Escríbenos por Messenger", contact_messenger_sub: "Respuestas rápidas en horario laboral", contact_telegram: "Escríbenos por Telegram", contact_telegram_sub: "Canal de contacto rápido 24/7", info_email_label: "Correo", info_phone_label: "Teléfono", info_address_label: "Dirección", info_address: "Ciudad Ho Chi Minh, Vietnam", info_hours_label: "Horario de atención", info_hours: "24/7 — Todos los días de la semana",
    footer_desc: "Proveedor líder y confiable de recursos para anuncios de Facebook, aliado de agencias y empresas en todo el mundo.", footer_rights: "Todos los derechos reservados.", footer_cta: "Contáctanos",
    chat_title: "Asistente de IA", chat_status_offline: "● Modo FAQ automático", chat_status_online: "● En línea", chat_direct_label: "¿Necesitas hablar con una persona?", chat_input_ph: "Escribe tu pregunta...", chat_greeting: "¡Hola! Soy tu asistente virtual. ¿En qué puedo ayudarte sobre nuestros recursos para anuncios de Facebook?", chat_fallback: "¡Gracias por tu pregunta! Para una asesoría más detallada, escribe directamente a nuestro equipo por Messenger o Telegram abajo.", chat_q_price: "¿Cuáles son los precios?", chat_q_warranty: "¿Hay garantía?", chat_q_delivery: "¿Qué tan rápida es la entrega?", chat_q_contact: "Hablar con un asesor", nav_company: "Empresa", company_tag: "Perfil de la Empresa", company_title: "Información de la Empresa", company_subtitle: "Información legal transparente y una mirada real a nuestro espacio de trabajo", label_legal_name: "Razón Social", label_tax_code: "Código Fiscal", label_founded: "Año de Fundación", label_hq_address: "Sede Principal", label_representative: "Representante", label_scale: "Tamaño del Equipo", label_field: "Sector de Actividad", gallery_empty_hint: "Las fotos de la empresa aparecerán aquí — agrégalas en el panel de administración (icono ⚙ en el pie de página)", contact_whatsapp: "Escríbenos por WhatsApp", contact_whatsapp_sub: "Soporte para clientes internacionales", contact_wechat: "Escríbenos por WeChat", contact_wechat_sub: "Para clientes en la región de China"
  },

  fr: {
    brand_tagline: "Ressources publicitaires Facebook", nav_about: "À propos", nav_services: "Services", nav_why: "Pourquoi nous", nav_process: "Processus", nav_testimonials: "Témoignages", nav_faq: "FAQ", nav_contact: "Contact", nav_cta: "Consulter maintenant",
    hero_badge: "Partenaire de confiance depuis 5+ ans", hero_title: "Partenaire de référence et de confiance pour les ressources publicitaires Facebook", hero_subtitle: "Plus de 5 ans à fournir des comptes publicitaires, des Business Manager, des cartes de paiement internationales et des solutions publicitaires à des milliers d'agences et d'entreprises dans le monde entier.", hero_cta_primary: "Consultation gratuite", hero_cta_secondary: "Voir les services", stat1_label: "Années d'expérience", stat2_label: "Clients fidèles", stat3_label: "Pays desservis", stat4_label: "Support technique",
    about_tag: "À propos de nous", about_title: "5 ans aux côtés de la communauté publicitaire mondiale", about_desc: "Nous sommes un fournisseur spécialisé de ressources publicitaires Facebook pour les agences et entreprises du monde entier, engagés pour la qualité, la transparence et un support dévoué 24/7.", about_li1: "Approvisionnement stable, rigoureusement vérifié avant livraison", about_li2: "Équipe technique résolvant les problèmes rapidement", about_li3: "Politique de garantie et de remboursement claire", about_li4: "Partenaire de milliers d'agences dans plus de 30 pays",
    services_tag: "Services", services_title: "Des ressources publicitaires Facebook complètes et de qualité", services_subtitle: "Des solutions tout-en-un pour des campagnes publicitaires stables et efficaces", svc1_t: "Comptes publicitaires", svc1_d: "Comptes multi-pays, plafonds élevés, bonne fiabilité, prêts à lancer une campagne immédiatement.", svc2_t: "Business Manager", svc2_d: "BM vérifié avec accès complet, stable sur le long terme pour gérer plusieurs comptes publicitaires.", svc3_t: "Cartes de paiement internationales", svc3_d: "Cartes Visa/Mastercard virtuelles pour des paiements publicitaires rapides et sécurisés.", svc4_t: "Fanpages fiables", svc4_d: "Pages de qualité, vérifiées, adaptées à de nombreux secteurs d'activité.", svc5_t: "Proxy et sécurité", svc5_d: "Proxies rapides et stables qui minimisent le risque de blocage de compte.", svc6_t: "Assistance checkpoint", svc6_d: "Une équipe dédiée résout les problèmes et fait appel des checkpoints rapidement, 24/7.",
    why_tag: "Pourquoi nous choisir", why_title: "Un partenaire fiable pour chaque campagne", why_subtitle: "Une confiance bâtie sur plus de 5 ans d'activité et des milliers de clients satisfaits", why1_t: "Réputation de premier plan", why1_d: "Plus de 5 ans d'activité transparente, la confiance de la communauté internationale des agences.", why2_t: "Qualité garantie", why2_d: "Chaque produit est rigoureusement vérifié avant la livraison.", why3_t: "Support 24/7", why3_d: "Notre équipe technique est toujours prête à vous aider, à tout moment.", why4_t: "Garantie claire", why4_d: "Une politique de garantie et de remplacement transparente qui protège vos droits.",
    process_tag: "Processus", process_title: "Simple - Rapide - Efficace", process_subtitle: "Seulement 4 étapes pour démarrer votre campagne publicitaire", step1_t: "Contactez-nous", step1_d: "Envoyez votre demande, notre équipe de conseillers vous contactera sous 15 minutes.", step2_t: "Choisissez une solution", step2_d: "Sélectionnez le produit adapté aux besoins de votre campagne.", step3_t: "Livraison et paiement", step3_d: "Recevez votre produit rapidement, avec un paiement flexible et sécurisé.", step4_t: "Accompagnement continu", step4_d: "Nous vous accompagnons tout au long de votre campagne.",
    partners_title: "La confiance des agences leaders",
    testi_tag: "Témoignages", testi_title: "Des milliers de clients satisfaits", testi_subtitle: "Des avis réels de nos partenaires", t1_quote: "« Service professionnel, comptes stables, support rapide. Nous collaborons depuis plus de 3 ans et sommes toujours satisfaits. »", t1_name: "Nguyen Minh Anh", t1_role: "Directrice d'agence, Hô-Chi-Minh-Ville", t2_quote: "« L'équipe de support technique résout les problèmes très rapidement, nos campagnes ne sont jamais interrompues. »", t2_name: "David Chen", t2_role: "Responsable marketing, Singapour",
    faq_tag: "FAQ", faq_title: "Questions fréquentes", q1: "Les produits sont-ils garantis ?", a1: "Oui, tous les produits bénéficient d'une politique de garantie et de remplacement claire et transparente.", q2: "Quel est le délai de livraison ?", a2: "La plupart des produits sont livrés dans les 15 à 30 minutes suivant la confirmation de commande.", q3: "Proposez-vous un support pour les clients internationaux ?", a3: "Oui, nous servons des clients dans plus de 30 pays avec une équipe de support multilingue.", q4: "Quels modes de paiement acceptez-vous ?", a4: "Nous prenons en charge de nombreux modes de paiement flexibles et sécurisés adaptés à chaque région.",
    contact_tag: "Contact", contact_title: "Prêt à lancer votre campagne ?", contact_subtitle: "Écrivez-nous directement sur Messenger ou Telegram — réponse rapide", contact_messenger: "Écrire sur Messenger", contact_messenger_sub: "Réponses rapides pendant les heures ouvrées", contact_telegram: "Écrire sur Telegram", contact_telegram_sub: "Canal de contact rapide 24/7", info_email_label: "E-mail", info_phone_label: "Téléphone", info_address_label: "Adresse", info_address: "Hô-Chi-Minh-Ville, Vietnam", info_hours_label: "Horaires", info_hours: "24/7 — Tous les jours de la semaine",
    footer_desc: "Fournisseur de référence et de confiance en ressources publicitaires Facebook, partenaire d'agences et d'entreprises dans le monde entier.", footer_rights: "Tous droits réservés.", footer_cta: "Nous contacter",
    chat_title: "Assistant IA", chat_status_offline: "● Mode FAQ automatique", chat_status_online: "● En ligne", chat_direct_label: "Besoin de parler à un humain ?", chat_input_ph: "Tapez votre question...", chat_greeting: "Bonjour ! Je suis votre assistant virtuel. Comment puis-je vous aider concernant nos ressources publicitaires Facebook ?", chat_fallback: "Merci pour votre question ! Pour une assistance plus détaillée, contactez directement notre équipe via Messenger ou Telegram ci-dessous.", chat_q_price: "Quels sont les tarifs ?", chat_q_warranty: "Y a-t-il une garantie ?", chat_q_delivery: "Quel est le délai de livraison ?", chat_q_contact: "Parler à un conseiller", nav_company: "Entreprise", company_tag: "Profil de l'Entreprise", company_title: "Informations sur l'Entreprise", company_subtitle: "Informations légales transparentes et un aperçu réel de notre espace de travail", label_legal_name: "Raison Sociale", label_tax_code: "Code Fiscal", label_founded: "Année de Création", label_hq_address: "Siège Social", label_representative: "Représentant", label_scale: "Taille de l'Équipe", label_field: "Secteur d'Activité", gallery_empty_hint: "Les photos de l'entreprise s'afficheront ici — ajoutez-les dans le panneau d'administration (icône ⚙ dans le pied de page)", contact_whatsapp: "Écrire sur WhatsApp", contact_whatsapp_sub: "Support pour les clients internationaux", contact_wechat: "Écrire sur WeChat", contact_wechat_sub: "Pour les clients de la région chinoise"
  },

  de: {
    brand_tagline: "Facebook-Werbe-Ressourcen", nav_about: "Über uns", nav_services: "Leistungen", nav_why: "Warum wir", nav_process: "Ablauf", nav_testimonials: "Referenzen", nav_faq: "FAQ", nav_contact: "Kontakt", nav_cta: "Jetzt beraten lassen",
    hero_badge: "Vertrauenswürdiger Partner seit über 5 Jahren", hero_title: "Führender, vertrauenswürdiger Partner für Facebook-Werbe-Ressourcen", hero_subtitle: "Seit über 5 Jahren beliefern wir tausende Agenturen und Unternehmen weltweit mit Werbekonten, Business Managern, internationalen Zahlungskarten und Werbelösungen.", hero_cta_primary: "Kostenlose Beratung", hero_cta_secondary: "Leistungen ansehen", stat1_label: "Jahre Erfahrung", stat2_label: "Zufriedene Kunden", stat3_label: "Bediente Länder", stat4_label: "Technischer Support",
    about_tag: "Über uns", about_title: "5 Jahre an der Seite der globalen Werbe-Community", about_desc: "Wir sind ein spezialisierter Anbieter von Facebook-Werbe-Ressourcen für Agenturen und Unternehmen weltweit — mit dem Versprechen von Qualität, Transparenz und engagiertem Support rund um die Uhr.", about_li1: "Stabile Versorgung, gründlich geprüft vor der Übergabe", about_li2: "Technisches Team löst Probleme schnell", about_li3: "Klare Garantie- und Rückerstattungsrichtlinie", about_li4: "Partnerschaft mit tausenden Agenturen in über 30 Ländern",
    services_tag: "Leistungen", services_title: "Umfassende, hochwertige Facebook-Werbe-Ressourcen", services_subtitle: "Komplettlösungen für stabile und effektive Werbekampagnen", svc1_t: "Werbekonten", svc1_d: "Werbekonten aus mehreren Ländern mit hohem Limit und gutem Trust-Score, sofort einsatzbereit.", svc2_t: "Business Manager", svc2_d: "Vollständig verifizierter BM mit vollem Zugriff, langfristig stabil für die Verwaltung mehrerer Konten.", svc3_t: "Internationale Zahlungskarten", svc3_d: "Virtuelle Visa-/Mastercard-Karten für schnelle, sichere Werbezahlungen.", svc4_t: "Vertrauenswürdige Fanpages", svc4_d: "Hochwertige, verifizierte Fanpages für viele Geschäftsbereiche.", svc5_t: "Proxy & Sicherheit", svc5_d: "Schnelle, stabile Proxies, die das Risiko einer Kontosperrung minimieren.", svc6_t: "Checkpoint-Support", svc6_d: "Ein spezialisiertes Team löst Probleme und legt rund um die Uhr schnell Einspruch gegen Checkpoints ein.",
    why_tag: "Warum wir", why_title: "Ein zuverlässiger Partner für jede Kampagne", why_subtitle: "Vertrauen, das über mehr als 5 Jahre und tausende zufriedene Kunden aufgebaut wurde", why1_t: "Führende Reputation", why1_d: "5+ Jahre transparenter Betrieb, dem Vertrauen der internationalen Agentur-Community.", why2_t: "Garantierte Qualität", why2_d: "Jedes Produkt wird vor der Übergabe gründlich geprüft.", why3_t: "24/7-Support", why3_d: "Unser technisches Team ist jederzeit für Sie da.", why4_t: "Klare Garantie", why4_d: "Transparente Garantie- und Ersatzrichtlinie zum Schutz Ihrer Rechte.",
    process_tag: "Ablauf", process_title: "Einfach - Schnell - Effektiv", process_subtitle: "Nur 4 Schritte, um Ihre Werbekampagne zu starten", step1_t: "Kontakt aufnehmen", step1_d: "Senden Sie Ihre Anfrage, unser Beraterteam meldet sich innerhalb von 15 Minuten.", step2_t: "Lösung auswählen", step2_d: "Wählen Sie das Produkt, das zu Ihrer Kampagne passt.", step3_t: "Übergabe & Zahlung", step3_d: "Schnelle Produktübergabe, flexible und sichere Zahlung.", step4_t: "Laufender Support", step4_d: "Wir begleiten Sie während der gesamten Kampagne.",
    partners_title: "Vertraut von führenden Agenturen",
    testi_tag: "Referenzen", testi_title: "Tausende zufriedene Kunden", testi_subtitle: "Echte Rückmeldungen unserer Partner", t1_quote: "„Professioneller Service, stabile Konten, schneller Support. Wir arbeiten seit über 3 Jahren zusammen und sind stets zufrieden.“", t1_name: "Nguyen Minh Anh", t1_role: "Agenturleiterin, Ho-Chi-Minh-Stadt", t2_quote: "„Das technische Support-Team löst Probleme sehr schnell, unsere Kampagnen laufen ohne Unterbrechung.“", t2_name: "David Chen", t2_role: "Marketing Manager, Singapur",
    faq_tag: "FAQ", faq_title: "Häufig gestellte Fragen", q1: "Gibt es eine Garantie auf die Produkte?", a1: "Ja, alle Produkte haben eine klare und transparente Garantie- und Ersatzrichtlinie.", q2: "Wie lange dauert die Lieferung?", a2: "Die meisten Produkte werden innerhalb von 15-30 Minuten nach Bestellbestätigung geliefert.", q3: "Unterstützen Sie internationale Kunden?", a3: "Ja, wir bedienen Kunden in über 30 Ländern mit einem mehrsprachigen Support-Team.", q4: "Welche Zahlungsmethoden werden akzeptiert?", a4: "Wir unterstützen mehrere flexible, sichere Zahlungsmethoden, angepasst an jede Region.",
    contact_tag: "Kontakt", contact_title: "Bereit, Ihre Kampagne zu starten?", contact_subtitle: "Schreiben Sie uns direkt über Messenger oder Telegram — schnelle Antwort", contact_messenger: "Über Messenger schreiben", contact_messenger_sub: "Schnelle Antworten während der Geschäftszeiten", contact_telegram: "Über Telegram schreiben", contact_telegram_sub: "Schneller 24/7-Kontaktkanal", info_email_label: "E-Mail", info_phone_label: "Telefon", info_address_label: "Adresse", info_address: "Ho-Chi-Minh-Stadt, Vietnam", info_hours_label: "Geschäftszeiten", info_hours: "24/7 — An jedem Wochentag",
    footer_desc: "Führender, vertrauenswürdiger Anbieter von Facebook-Werbe-Ressourcen, Partner von Agenturen und Unternehmen weltweit.", footer_rights: "Alle Rechte vorbehalten.", footer_cta: "Kontaktieren Sie uns",
    chat_title: "KI-Assistent", chat_status_offline: "● Automatischer FAQ-Modus", chat_status_online: "● Online", chat_direct_label: "Brauchen Sie einen Menschen?", chat_input_ph: "Geben Sie Ihre Frage ein...", chat_greeting: "Hallo! Ich bin Ihr virtueller Assistent. Wobei kann ich zu unseren Facebook-Werbe-Ressourcen helfen?", chat_fallback: "Danke für Ihre Frage! Für eine ausführliche Beratung schreiben Sie unserem Team direkt über Messenger oder Telegram unten.", chat_q_price: "Wie hoch sind die Preise?", chat_q_warranty: "Gibt es eine Garantie?", chat_q_delivery: "Wie schnell ist die Lieferung?", chat_q_contact: "Mit einem Berater sprechen", nav_company: "Unternehmen", company_tag: "Unternehmensprofil", company_title: "Unternehmensinformationen", company_subtitle: "Transparente rechtliche Informationen und ein echter Einblick in unseren Arbeitsplatz", label_legal_name: "Firmenname", label_tax_code: "Steuernummer", label_founded: "Gründungsjahr", label_hq_address: "Hauptsitz", label_representative: "Vertreter", label_scale: "Teamgröße", label_field: "Geschäftsbereich", gallery_empty_hint: "Unternehmensfotos werden hier angezeigt — fügen Sie sie im Admin-Panel hinzu (⚙-Symbol in der Fußzeile)", contact_whatsapp: "Über WhatsApp schreiben", contact_whatsapp_sub: "Support für internationale Kunden", contact_wechat: "Über WeChat schreiben", contact_wechat_sub: "Für Kunden in der Region China"
  },

  pt: {
    brand_tagline: "Recursos para Anúncios do Facebook", nav_about: "Sobre nós", nav_services: "Serviços", nav_why: "Por que nos escolher", nav_process: "Processo", nav_testimonials: "Depoimentos", nav_faq: "Perguntas frequentes", nav_contact: "Contato", nav_cta: "Falar agora",
    hero_badge: "Parceiro de confiança há mais de 5 anos", hero_title: "Parceiro líder e confiável em recursos para anúncios do Facebook", hero_subtitle: "Há mais de 5 anos fornecendo contas de anúncios, Business Manager, cartões de pagamento internacionais e soluções de anúncios para milhares de agências e empresas em todo o mundo.", hero_cta_primary: "Consultoria gratuita", hero_cta_secondary: "Ver serviços", stat1_label: "Anos de experiência", stat2_label: "Clientes confiantes", stat3_label: "Países atendidos", stat4_label: "Suporte técnico",
    about_tag: "Sobre nós", about_title: "5 anos ao lado da comunidade global de anúncios", about_desc: "Somos um fornecedor especializado em recursos para anúncios do Facebook para agências e empresas em todo o mundo, comprometidos com qualidade, transparência e suporte dedicado 24/7.", about_li1: "Fornecimento estável, verificado rigorosamente antes da entrega", about_li2: "Equipe técnica que resolve problemas rapidamente", about_li3: "Política clara de garantia e reembolso", about_li4: "Parceria com milhares de agências em mais de 30 países",
    services_tag: "Serviços", services_title: "Recursos completos e de qualidade para anúncios do Facebook", services_subtitle: "Soluções completas para campanhas estáveis e eficazes", svc1_t: "Contas de anúncios", svc1_d: "Contas multi-país, limites altos, boa confiabilidade, prontas para campanhas imediatas.", svc2_t: "Business Manager", svc2_d: "BM verificado com acesso total, estável a longo prazo para gerenciar várias contas.", svc3_t: "Cartões de pagamento internacionais", svc3_d: "Cartões Visa/Mastercard virtuais para pagamentos de anúncios rápidos e seguros.", svc4_t: "Fanpages confiáveis", svc4_d: "Páginas de qualidade e verificadas, adequadas para diversos setores.", svc5_t: "Proxy e segurança", svc5_d: "Proxies rápidos e estáveis que reduzem o risco de bloqueio de conta.", svc6_t: "Suporte para checkpoints", svc6_d: "Equipe especializada resolve problemas e recorre de checkpoints rapidamente, 24/7.",
    why_tag: "Por que nos escolher", why_title: "Um parceiro confiável para cada campanha", why_subtitle: "Confiança construída ao longo de mais de 5 anos e milhares de clientes satisfeitos", why1_t: "Reputação líder", why1_d: "Mais de 5 anos de operação transparente, com a confiança da comunidade internacional de agências.", why2_t: "Qualidade garantida", why2_d: "Cada produto é rigorosamente verificado antes da entrega.", why3_t: "Suporte 24/7", why3_d: "Nossa equipe técnica está sempre pronta para ajudar, a qualquer hora.", why4_t: "Garantia clara", why4_d: "Política de garantia e substituição transparente que protege os direitos do cliente.",
    process_tag: "Processo", process_title: "Simples - Rápido - Eficaz", process_subtitle: "Apenas 4 passos para iniciar sua campanha", step1_t: "Entre em contato", step1_d: "Envie sua solicitação, nossa equipe entrará em contato em 15 minutos.", step2_t: "Escolha uma solução", step2_d: "Selecione o produto adequado às necessidades da sua campanha.", step3_t: "Entrega e pagamento", step3_d: "Receba seu produto rapidamente, com pagamento flexível e seguro.", step4_t: "Suporte contínuo", step4_d: "Acompanhamos você durante toda a campanha.",
    partners_title: "A confiança das principais agências",
    testi_tag: "Depoimentos", testi_title: "Milhares de clientes satisfeitos", testi_subtitle: "Opiniões reais dos nossos parceiros", t1_quote: "\"Serviço profissional, contas estáveis, suporte rápido. Trabalhamos juntos há mais de 3 anos e sempre satisfeitos.\"", t1_name: "Nguyen Minh Anh", t1_role: "Diretora de Agência, Cidade de Ho Chi Minh", t2_quote: "\"A equipe de suporte técnico resolve problemas muito rapidamente, nossas campanhas nunca são interrompidas.\"", t2_name: "David Chen", t2_role: "Gerente de Marketing, Singapura",
    faq_tag: "Perguntas frequentes", faq_title: "Perguntas frequentes", q1: "Os produtos têm garantia?", a1: "Sim, todos os produtos têm uma política de garantia e substituição clara e transparente.", q2: "Quanto tempo leva a entrega?", a2: "A maioria dos produtos é entregue em 15-30 minutos após a confirmação do pedido.", q3: "Vocês atendem clientes internacionais?", a3: "Sim, atendemos clientes em mais de 30 países com uma equipe de suporte multilíngue.", q4: "Quais métodos de pagamento são aceitos?", a4: "Suportamos vários métodos de pagamento flexíveis e seguros, adaptados a cada região.",
    contact_tag: "Contato", contact_title: "Pronto para lançar sua campanha?", contact_subtitle: "Fale conosco diretamente pelo Messenger ou Telegram — resposta rápida", contact_messenger: "Falar pelo Messenger", contact_messenger_sub: "Respostas rápidas em horário comercial", contact_telegram: "Falar pelo Telegram", contact_telegram_sub: "Canal de contato rápido 24/7", info_email_label: "E-mail", info_phone_label: "Telefone", info_address_label: "Endereço", info_address: "Cidade de Ho Chi Minh, Vietnã", info_hours_label: "Horário de funcionamento", info_hours: "24/7 — Todos os dias da semana",
    footer_desc: "Fornecedor líder e confiável de recursos para anúncios do Facebook, parceiro de agências e empresas em todo o mundo.", footer_rights: "Todos os direitos reservados.", footer_cta: "Fale conosco",
    chat_title: "Assistente de IA", chat_status_offline: "● Modo FAQ automático", chat_status_online: "● Online", chat_direct_label: "Precisa falar com um atendente?", chat_input_ph: "Digite sua pergunta...", chat_greeting: "Olá! Sou seu assistente virtual. Como posso ajudar sobre nossos recursos para anúncios do Facebook?", chat_fallback: "Obrigado pela pergunta! Para uma consultoria mais detalhada, fale diretamente com nossa equipe pelo Messenger ou Telegram abaixo.", chat_q_price: "Quais são os preços?", chat_q_warranty: "Há garantia?", chat_q_delivery: "Quão rápida é a entrega?", chat_q_contact: "Falar com um consultor", nav_company: "Empresa", company_tag: "Perfil da Empresa", company_title: "Informações da Empresa", company_subtitle: "Informações legais transparentes e um panorama real do nosso espaço de trabalho", label_legal_name: "Razão Social", label_tax_code: "Código Fiscal", label_founded: "Ano de Fundação", label_hq_address: "Sede Principal", label_representative: "Representante", label_scale: "Tamanho da Equipe", label_field: "Área de Atuação", gallery_empty_hint: "As fotos da empresa aparecerão aqui — adicione-as no painel de administração (ícone ⚙ no rodapé)", contact_whatsapp: "Falar pelo WhatsApp", contact_whatsapp_sub: "Suporte para clientes internacionais", contact_wechat: "Falar pelo WeChat", contact_wechat_sub: "Para clientes da região da China"
  },

  ar: {
    brand_tagline: "موارد إعلانات فيسبوك", nav_about: "من نحن", nav_services: "خدماتنا", nav_why: "لماذا نحن", nav_process: "آلية العمل", nav_testimonials: "آراء العملاء", nav_faq: "الأسئلة الشائعة", nav_contact: "تواصل معنا", nav_cta: "استشارة الآن",
    hero_badge: "شريك موثوق منذ أكثر من 5 سنوات", hero_title: "الشريك الرائد والموثوق في موارد إعلانات فيسبوك", hero_subtitle: "أكثر من 5 سنوات في توفير حسابات إعلانية، وبيزنس مانجر، وبطاقات دفع دولية، وحلول إعلانية لآلاف الوكالات والشركات حول العالم.", hero_cta_primary: "احصل على استشارة مجانية", hero_cta_secondary: "عرض الخدمات", stat1_label: "سنوات الخبرة", stat2_label: "عملاء واثقون", stat3_label: "دول نخدمها", stat4_label: "الدعم الفني",
    about_tag: "من نحن", about_title: "5 سنوات إلى جانب مجتمع الإعلانات العالمي", about_desc: "نحن مزود متخصص في موارد إعلانات فيسبوك للوكالات والشركات حول العالم، ملتزمون بالجودة والشفافية والدعم المتفاني على مدار الساعة.", about_li1: "توريد مستقر، يتم التحقق منه بدقة قبل التسليم", about_li2: "فريق فني يحل المشكلات بسرعة", about_li3: "سياسة ضمان واسترداد واضحة", about_li4: "شراكة مع آلاف الوكالات في أكثر من 30 دولة",
    services_tag: "خدماتنا", services_title: "موارد إعلانات فيسبوك كاملة وعالية الجودة", services_subtitle: "حلول متكاملة لتشغيل حملاتك الإعلانية بثبات وفعالية", svc1_t: "حسابات إعلانية", svc1_d: "حسابات متعددة الدول بحدود إنفاق عالية وموثوقية جيدة، جاهزة لبدء الحملات فوراً.", svc2_t: "بيزنس مانجر", svc2_d: "بيزنس مانجر موثق بصلاحيات كاملة، مستقر على المدى الطويل لإدارة عدة حسابات إعلانية.", svc3_t: "بطاقات دفع دولية", svc3_d: "بطاقات فيزا/ماستركارد افتراضية لدفع تكاليف الإعلانات بسرعة وأمان.", svc4_t: "صفحات موثوقة", svc4_d: "صفحات عالية الجودة وموثقة، مناسبة لمختلف المجالات التجارية.", svc5_t: "بروكسي وأمان", svc5_d: "بروكسي عالي السرعة ومستقر يقلل من خطر حظر الحساب.", svc6_t: "دعم حل مشاكل Checkpoint", svc6_d: "فريق متخصص يحل المشكلات ويستأنف حالات الحظر بسرعة على مدار الساعة.",
    why_tag: "لماذا نحن", why_title: "شريك موثوق لكل حملة إعلانية", why_subtitle: "ثقة بُنيت على مدار أكثر من 5 سنوات وآلاف العملاء الراضين", why1_t: "سمعة رائدة", why1_d: "أكثر من 5 سنوات من العمل الشفاف، حاصلون على ثقة مجتمع الوكالات الدولي.", why2_t: "جودة مضمونة", why2_d: "يتم التحقق من كل منتج بدقة قبل التسليم.", why3_t: "دعم على مدار الساعة", why3_d: "فريقنا الفني جاهز دائماً للمساعدة في أي وقت وأي مكان.", why4_t: "ضمان واضح", why4_d: "سياسة ضمان واستبدال شفافة تحمي حقوق العملاء.",
    process_tag: "آلية العمل", process_title: "بسيطة - سريعة - فعّالة", process_subtitle: "4 خطوات فقط لبدء حملتك الإعلانية", step1_t: "تواصل معنا", step1_d: "أرسل طلبك وسيتواصل معك فريق الاستشارات خلال 15 دقيقة.", step2_t: "اختر الحل المناسب", step2_d: "اختر المنتج الذي يناسب احتياجات حملتك.", step3_t: "التسليم والدفع", step3_d: "استلم منتجك بسرعة مع خيارات دفع مرنة وآمنة.", step4_t: "دعم مستمر", step4_d: "نرافقك طوال فترة تشغيل حملتك الإعلانية.",
    partners_title: "موثوق به من قبل الوكالات الرائدة",
    testi_tag: "آراء العملاء", testi_title: "آلاف العملاء الراضين", testi_subtitle: "آراء حقيقية من شركائنا", t1_quote: "«خدمة احترافية، حسابات مستقرة، دعم سريع. نتعاون منذ أكثر من 3 سنوات وراضون دائماً.»", t1_name: "نغوين مين آنه", t1_role: "مديرة وكالة، مدينة هوشي منه", t2_quote: "«فريق الدعم الفني يحل المشكلات بسرعة كبيرة، حملاتنا لا تتوقف أبداً.»", t2_name: "ديفيد تشن", t2_role: "مدير تسويق، سنغافورة",
    faq_tag: "الأسئلة الشائعة", faq_title: "الأسئلة الشائعة", q1: "هل المنتجات مضمونة؟", a1: "نعم، جميع المنتجات تشمل سياسة ضمان واستبدال واضحة وشفافة.", q2: "كم يستغرق تسليم المنتج؟", a2: "يتم تسليم معظم المنتجات خلال 15-30 دقيقة بعد تأكيد الطلب.", q3: "هل تدعمون العملاء الدوليين؟", a3: "نعم، نخدم عملاء في أكثر من 30 دولة مع فريق دعم متعدد اللغات.", q4: "ما هي طرق الدفع المقبولة؟", a4: "ندعم طرق دفع متعددة ومرنة وآمنة تناسب كل منطقة.",
    contact_tag: "تواصل معنا", contact_title: "هل أنت مستعد لبدء حملتك؟", contact_subtitle: "راسلنا مباشرة عبر Messenger أو Telegram — رد سريع", contact_messenger: "راسلنا عبر Messenger", contact_messenger_sub: "ردود سريعة خلال ساعات العمل", contact_telegram: "راسلنا عبر Telegram", contact_telegram_sub: "قناة تواصل سريعة على مدار الساعة", info_email_label: "البريد الإلكتروني", info_phone_label: "الهاتف", info_address_label: "العنوان", info_address: "مدينة هوشي منه، فيتنام", info_hours_label: "ساعات العمل", info_hours: "على مدار الساعة طوال أيام الأسبوع",
    footer_desc: "مزود رائد وموثوق لموارد إعلانات فيسبوك، شريك للوكالات والشركات حول العالم.", footer_rights: "جميع الحقوق محفوظة.", footer_cta: "تواصل معنا",
    chat_title: "مساعد الذكاء الاصطناعي", chat_status_offline: "● وضع الأسئلة الشائعة التلقائي", chat_status_online: "● متصل", chat_direct_label: "تحتاج للتحدث مع شخص؟", chat_input_ph: "اكتب سؤالك...", chat_greeting: "مرحباً! أنا مساعدك الافتراضي. كيف يمكنني مساعدتك بخصوص موارد إعلانات فيسبوك؟", chat_fallback: "شكراً لسؤالك! للحصول على مساعدة تفصيلية، يرجى مراسلة فريقنا مباشرة عبر Messenger أو Telegram أدناه.", chat_q_price: "ما هي الأسعار؟", chat_q_warranty: "هل يوجد ضمان؟", chat_q_delivery: "كم يستغرق التسليم؟", chat_q_contact: "التحدث مع مستشار", nav_company: "الشركة", company_tag: "ملف الشركة", company_title: "معلومات الشركة", company_subtitle: "معلومات قانونية شفافة ولمحة حقيقية عن مساحة عملنا", label_legal_name: "الاسم القانوني", label_tax_code: "الرقم الضريبي", label_founded: "سنة التأسيس", label_hq_address: "المقر الرئيسي", label_representative: "الممثل القانوني", label_scale: "حجم الفريق", label_field: "مجال العمل", gallery_empty_hint: "ستظهر صور الشركة هنا — أضفها من لوحة التحكم (أيقونة ⚙ في أسفل الصفحة)", contact_whatsapp: "راسلنا عبر WhatsApp", contact_whatsapp_sub: "دعم للعملاء الدوليين", contact_wechat: "راسلنا عبر WeChat", contact_wechat_sub: "لعملاء منطقة الصين"
  },

  hi: {
    brand_tagline: "फेसबुक विज्ञापन संसाधन", nav_about: "हमारे बारे में", nav_services: "सेवाएं", nav_why: "हमें क्यों चुनें", nav_process: "प्रक्रिया", nav_testimonials: "ग्राहक समीक्षा", nav_faq: "सामान्य प्रश्न", nav_contact: "संपर्क करें", nav_cta: "अभी परामर्श लें",
    hero_badge: "5+ वर्षों से विश्वसनीय साझेदार", hero_title: "फेसबुक विज्ञापन संसाधनों के लिए अग्रणी, विश्वसनीय साझेदार", hero_subtitle: "5 वर्षों से अधिक समय से विश्व भर की हजारों एजेंसियों और व्यवसायों को विज्ञापन खाते, बिज़नेस मैनेजर, अंतरराष्ट्रीय भुगतान कार्ड और विज्ञापन समाधान प्रदान कर रहे हैं।", hero_cta_primary: "निःशुल्क परामर्श लें", hero_cta_secondary: "सेवाएं देखें", stat1_label: "वर्षों का अनुभव", stat2_label: "विश्वसनीय ग्राहक", stat3_label: "सेवा प्राप्त देश", stat4_label: "तकनीकी सहायता",
    about_tag: "हमारे बारे में", about_title: "वैश्विक विज्ञापन समुदाय के साथ 5 वर्ष", about_desc: "हम विश्व भर की एजेंसियों और व्यवसायों के लिए फेसबुक विज्ञापन संसाधन प्रदान करने वाली एक विशेषज्ञ कंपनी हैं, जो गुणवत्ता, पारदर्शिता और 24/7 समर्पित सहायता के लिए प्रतिबद्ध है।", about_li1: "स्थिर आपूर्ति, सुपुर्दगी से पहले सख्ती से सत्यापित", about_li2: "तकनीकी टीम समस्याओं को तेज़ी से हल करती है", about_li3: "स्पष्ट वारंटी और रिफंड नीति", about_li4: "30+ देशों की हजारों एजेंसियों के साथ साझेदारी",
    services_tag: "सेवाएं", services_title: "संपूर्ण, उच्च-गुणवत्ता वाले फेसबुक विज्ञापन संसाधन", services_subtitle: "आपके विज्ञापन अभियानों को स्थिर और प्रभावी बनाए रखने के लिए ऑल-इन-वन समाधान", svc1_t: "विज्ञापन खाते", svc1_d: "उच्च सीमा और अच्छे ट्रस्ट स्कोर वाले बहु-देशीय विज्ञापन खाते, तुरंत अभियान शुरू करने के लिए तैयार।", svc2_t: "बिज़नेस मैनेजर", svc2_d: "पूर्ण एक्सेस के साथ सत्यापित बीएम, कई विज्ञापन खातों के प्रबंधन के लिए दीर्घकालिक स्थिर।", svc3_t: "अंतरराष्ट्रीय भुगतान कार्ड", svc3_d: "तेज़, सुरक्षित विज्ञापन भुगतान के लिए वर्चुअल वीज़ा/मास्टरकार्ड कार्ड।", svc4_t: "विश्वसनीय फैनपेज", svc4_d: "गुणवत्तापूर्ण, सत्यापित फैनपेज, कई व्यावसायिक क्षेत्रों के लिए उपयुक्त।", svc5_t: "प्रॉक्सी और सुरक्षा", svc5_d: "हाई-स्पीड, स्थिर प्रॉक्सी जो खाता ब्लॉक होने के जोखिम को कम करती है।", svc6_t: "चेकपॉइंट सहायता", svc6_d: "एक समर्पित टीम 24/7 समस्याओं का समाधान करती है और चेकपॉइंट की तेज़ी से अपील करती है।",
    why_tag: "हमें क्यों चुनें", why_title: "हर अभियान के लिए एक विश्वसनीय साझेदार", why_subtitle: "5+ वर्षों के संचालन और हजारों संतुष्ट ग्राहकों से बना विश्वास", why1_t: "अग्रणी प्रतिष्ठा", why1_d: "5+ वर्षों का पारदर्शी संचालन, अंतरराष्ट्रीय एजेंसी समुदाय द्वारा विश्वसनीय।", why2_t: "गारंटीकृत गुणवत्ता", why2_d: "हर उत्पाद की सुपुर्दगी से पहले सख्ती से जांच की जाती है।", why3_t: "24/7 सहायता", why3_d: "हमारी तकनीकी टीम हर समय, हर जगह मदद के लिए तैयार रहती है।", why4_t: "स्पष्ट वारंटी", why4_d: "पारदर्शी वारंटी और प्रतिस्थापन नीति जो ग्राहकों के अधिकारों की रक्षा करती है।",
    process_tag: "प्रक्रिया", process_title: "सरल - तेज़ - प्रभावी", process_subtitle: "आपके विज्ञापन अभियान को शुरू करने के लिए केवल 4 चरण", step1_t: "संपर्क करें", step1_d: "अपना अनुरोध भेजें, हमारी परामर्श टीम 15 मिनट के भीतर संपर्क करेगी।", step2_t: "समाधान चुनें", step2_d: "अपने अभियान की जरूरतों के अनुसार उत्पाद चुनें।", step3_t: "सुपुर्दगी और भुगतान", step3_d: "अपना उत्पाद जल्दी प्राप्त करें, लचीला और सुरक्षित भुगतान।", step4_t: "निरंतर सहायता", step4_d: "हम आपके पूरे अभियान के दौरान आपके साथ रहते हैं।",
    partners_title: "अग्रणी एजेंसियों द्वारा विश्वसनीय",
    testi_tag: "ग्राहक समीक्षा", testi_title: "हजारों संतुष्ट ग्राहक", testi_subtitle: "हमारे साझेदारों की वास्तविक प्रतिक्रिया", t1_quote: "\"पेशेवर सेवा, स्थिर खाते, तेज़ सहायता। 3 वर्षों से अधिक समय से साथ काम कर रहे हैं और हमेशा संतुष्ट हैं।\"", t1_name: "न्गुयेन मिन्ह आन्ह", t1_role: "एजेंसी निदेशक, हो ची मिन्ह सिटी", t2_quote: "\"तकनीकी सहायता टीम बहुत तेज़ी से समस्याओं का समाधान करती है, हमारे अभियान कभी बाधित नहीं होते।\"", t2_name: "डेविड चेन", t2_role: "मार्केटिंग मैनेजर, सिंगापुर",
    faq_tag: "सामान्य प्रश्न", faq_title: "अक्सर पूछे जाने वाले प्रश्न", q1: "क्या उत्पादों पर वारंटी है?", a1: "हां, सभी उत्पादों में स्पष्ट और पारदर्शी वारंटी और प्रतिस्थापन नीति है।", q2: "उत्पाद की सुपुर्दगी में कितना समय लगता है?", a2: "अधिकांश उत्पाद ऑर्डर की पुष्टि के 15-30 मिनट के भीतर सुपुर्द किए जाते हैं।", q3: "क्या आप अंतरराष्ट्रीय ग्राहकों की सहायता करते हैं?", a3: "हां, हम बहुभाषी सहायता टीम के साथ 30+ देशों के ग्राहकों की सेवा करते हैं।", q4: "किन भुगतान विधियों को स्वीकार किया जाता है?", a4: "हम प्रत्येक क्षेत्र के अनुरूप कई लचीली, सुरक्षित भुगतान विधियों का समर्थन करते हैं।",
    contact_tag: "संपर्क करें", contact_title: "क्या आप अपना अभियान शुरू करने के लिए तैयार हैं?", contact_subtitle: "Messenger या Telegram पर सीधे हमें संदेश भेजें — तेज़ प्रतिक्रिया", contact_messenger: "Messenger पर संदेश भेजें", contact_messenger_sub: "कार्य समय में तेज़ जवाब", contact_telegram: "Telegram पर संदेश भेजें", contact_telegram_sub: "24/7 त्वरित संपर्क चैनल", info_email_label: "ईमेल", info_phone_label: "फोन", info_address_label: "पता", info_address: "हो ची मिन्ह सिटी, वियतनाम", info_hours_label: "कार्य समय", info_hours: "24/7 — सप्ताह के हर दिन",
    footer_desc: "फेसबुक विज्ञापन संसाधनों के अग्रणी, विश्वसनीय प्रदाता, विश्व भर की एजेंसियों और व्यवसायों के साझेदार।", footer_rights: "सर्वाधिकार सुरक्षित।", footer_cta: "संपर्क करें",
    chat_title: "AI सहायक", chat_status_offline: "● ऑटो-FAQ मोड", chat_status_online: "● ऑनलाइन", chat_direct_label: "किसी व्यक्ति से बात करनी है?", chat_input_ph: "अपना प्रश्न टाइप करें...", chat_greeting: "नमस्ते! मैं आपका वर्चुअल सहायक हूं। फेसबुक विज्ञापन संसाधनों के बारे में आपको क्या मदद चाहिए?", chat_fallback: "आपके प्रश्न के लिए धन्यवाद! विस्तृत सहायता के लिए, कृपया नीचे Messenger या Telegram के माध्यम से सीधे हमारी टीम से संपर्क करें।", chat_q_price: "कीमत क्या है?", chat_q_warranty: "क्या वारंटी है?", chat_q_delivery: "डिलीवरी कितनी जल्दी होती है?", chat_q_contact: "सलाहकार से बात करें", nav_company: "कंपनी", company_tag: "कंपनी प्रोफ़ाइल", company_title: "कंपनी की जानकारी", company_subtitle: "पारदर्शी कानूनी जानकारी और हमारे कार्यक्षेत्र की वास्तविक झलक", label_legal_name: "कानूनी नाम", label_tax_code: "टैक्स कोड", label_founded: "स्थापना वर्ष", label_hq_address: "मुख्यालय", label_representative: "प्रतिनिधि", label_scale: "टीम का आकार", label_field: "व्यवसाय क्षेत्र", gallery_empty_hint: "कंपनी की तस्वीरें यहाँ दिखाई देंगी — एडमिन पैनल (फुटर में ⚙ आइकन) में जोड़ें", contact_whatsapp: "WhatsApp पर संदेश भेजें", contact_whatsapp_sub: "अंतरराष्ट्रीय ग्राहकों के लिए सहायता", contact_wechat: "WeChat पर संदेश भेजें", contact_wechat_sub: "चीन क्षेत्र के ग्राहकों के लिए"
  }
};
